### ISSUE TITLE
Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by deepakverma4** [LonelyCpp/react-native-youtube-iframe#10]
getting error **Tried to register two views with the same name RNCWebView** after installing ```react-native-youtube-iframe```

**Comment by LonelyCpp** [comment]
This seems to be a problem with your webview installation. 

You can refer to this issue for more info - https://github.com/react-native-community/react-native-webview/issues/373

Can you list the dependencies you have in your project? (contents of the file `package.json`)

**Comment by deepakverma4** [comment]
@LonelyCpp  
```
dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-webview": "^9.0.2",
    "react-native-youtube-iframe": "^1.2.0",
  }
```

**Comment by LonelyCpp** [comment]
It seems like the latest `react-native-webview` only supports react native version 0.60 and above 😓 

can you change the version to `6.11.1` and try it? 

`"react-native-webview": "6.11.1",`

**Comment by deepakverma4** [comment]
Solved by upgrading ```react-native-webview```
