### ISSUE TITLE
React native Android 11 : crash issue 

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [LonelyCpp/react-native-youtube-iframe#101]
The app is crashed after open a screen that contains` react-native-youtube-iframe` component using react native navigation v5.

**Comment by LonelyCpp** [comment]
Hey, I've faced this issue as well. This usually happens on android with the default screen transition on react navigation v5. 

Its a bug in react-native-webview, where it crashes when react-navigation tries to animate its opacity. Here are a few threads you can follow - [430](https://github.com/react-native-webview/react-native-webview/issues/430), [811](https://github.com/react-native-webview/react-native-webview/issues/811)

I've personally use a workaround where I override the default animation with a more simple slide transition for screens that have the youtube player (or webviews). Use [transitionpresets](https://reactnavigation.org/docs/stack-navigator/#transitionpresets) to choose a transition that doesn't involve opacity animations

**Comment by arslanyakup** [comment]
Hello there,

I had the same crash situation and the following code block for "react navigation v4" prevented the crash.

`navigationOptions: { animationEnabled: false }`

**Comment by aj0911** [comment]
Getting this error, while opening a screen which contains youtubePlayer

Invariant Violation: Failed to call into JavaScript module method WebViewMessageHandler11.onMessage(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 12): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry, RCTEventEmitter, RNCWebViewMessagingModule.
          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
