### ISSUE TITLE
Android: display auto turns off while the video is playing in fullscreen

### ISSUE THREAD

**Issue by aakashr143** [LonelyCpp/react-native-youtube-iframe#102]
The display auto turns off while the video is playing on fullscreen but doesnt when the video isnt playing on fullscreen. This only happens on android

**Comment by LonelyCpp** [comment]
you can programmatically tell the device not to sleep when a video is active -
* expo - https://docs.expo.io/versions/latest/sdk/keep-awake
* non-expo - https://www.npmjs.com/package/react-native-keep-awake

**Comment by aakashr143** [comment]
Thanks for the help
