### ISSUE TITLE
Disable video information and options

### ISSUE THREAD

**Issue by CodeDruid13** [LonelyCpp/react-native-youtube-iframe#103]
**Describe the bug**
It's not a bug but rather annoying feature of the embed, whenever a user taps and holds anywhere outside the play button, it opens up the youtube menu like stats for nerds, copy video url... same as how the official player does when right clicking on the video

**To Reproduce** 
Tap and hold on video without tapping on the play button

**Expected behavior** 
To play the video whenever tapped or atleast not show the menu

**Screenshots**
[DropBox Link](https://www.dropbox.com/s/cvg1gpua87t24xf/Screenshot_1612167116.png?dl=0)

**Smartphone (please complete the following information):**
 - Device: iPhone11, Pixel 3a, Samsung S9+
 - OS + version: [ios 14.4, Android 10
 - `react-native-youtube-iframe` version 1.3.0
 - `react-native-webview` version 10.8.3
 - `Expo` verison [if using expo]

**Comment by LonelyCpp** [comment]
Hi @CodeDruid13 

Officially there is no way to disable this menu, and it is against the youtube ToS to modify the iframe or add overlays.

If you really want to disable this, you could try
* overlaying the player with a touchable (this will disable interactions with the player, you will have to implement play / pause / seek)
* add a gesture handler that responds only to long presses.
