### ISSUE TITLE
Video not getting pause on scroll or while navigating to other page  in ios

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [LonelyCpp/react-native-youtube-iframe#104]
videos are not getting paused  when user scroll page and videos goes out of screen .
while user navigate to other page even than video is not pausing.

ios only

**Comment by LonelyCpp** [comment]
Hi, the component does not handle play / pause when the player goes off screen. You'll have to handle it yourself.

If videos are stopping, its probably some flatList optimization where Views are unmounted when scrolled off screen

**Comment by LonelyCpp** [comment]
you can use [onviewableitemschanged](https://reactnative.dev/docs/flatlist#onviewableitemschanged) on a flatlist to easily handle this
