### ISSUE TITLE
Ads dont play before the video

### ISSUE THREAD

**Issue by aakashr143** [LonelyCpp/react-native-youtube-iframe#105]
On both iOS and android ads dont play before the video 
- iphone 11 Pro Max running iOS 13
- iphone 5 S running iOS 12
- Nokia 3.4 running android 10

**Comment by LonelyCpp** [comment]
since there is no domain for the iframe to verify, youtube will not play ads. (#98 too is a related issue)

**Comment by prisar** [comment]
Is it ok if ads are not displayed. will it be in compliance of YouTube policy

**Comment by LonelyCpp** [comment]
@prisar definitely not a violation of policy. The library itself does nothing to prevent ads, youtube decides this based on the origin URL

**Comment by prisar** [comment]
@LonelyCpp  My app just got removed from the store for being non-compliant in Youtube policies. Earlier I got a review rejected for playing the video in background. Which actually was not happening. I am not sure why, thought that it maybe related to displaying ads. Currently, there are not ads in the app.

**Comment by LonelyCpp** [comment]
it's unlikely to be because of ads. The youtube native sdk (provided by google) also does not show ads.

The background play might be the cause since google has some automated tests to check this. To be 100% sure, use [AppState](https://reactnative.dev/docs/appstate) to only render the component if currentState is `active`.

**Comment by LonelyCpp** [comment]
here's another related thread - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/72

**Comment by prisar** [comment]
@LonelyCpp After putting the condition for currentState to be `inactive` and `background` seems to be compliant. [#72](url) has the same issue from what I have read. It really helped. 
Now the app is available again:)
