### ISSUE TITLE
WARN Did not receive response to shouldStartLoad in time, defaulting to YES

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [LonelyCpp/react-native-youtube-iframe#106]
after upgrade RN to 0.63.4 I got the below WARN : 
WARN  startLoadWithResult invoked with invalid lockIdentifier: got 3973002971, expected 3470444362
WARN     Did not receive response to shouldStartLoad in time, defaulting to YES

 - Simulator: [e.g. iPhone12]
 - OS + version: [e.g. iOS 14.3]
 - `react-native-youtube-iframe` ^1.4.0 
 - `react-native-webview` ^11.2.1

**Comment by LonelyCpp** [comment]
Hey, I could not recreate such a warning. It seems to be coming from the webview when debug mode it turned on. More info here - https://github.com/react-native-webview/react-native-webview/issues/124

I don't think it will be a problem in production.
