### ISSUE TITLE
Long press on the video gives unwanted debug information and url info

### ISSUE THREAD

**Issue by vijay122** [LonelyCpp/react-native-youtube-iframe#107]
LongPress on any of the video which is in playing condition is enabling options. Can we have control, whether to display the options or not. because facebook or youtube is able to block this popup. We should also try to stop as it is exposing unwanted data to the viewer.

**To Reproduce**
press and hold on any video tile which is in playing mode. it is opening a grey color menu with debug , video informations.

**Expected behavior**
Need to have a flag, to hide or prevent the longpress options.
**Screenshots**
Android emulator and devices [applicable.](url)
**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` version 
 - `react-native-webview` version
 - `Expo` verison [if using expo]
![image](https://user-images.githubusercontent.com/16363856/107254246-23334f00-6a5d-11eb-842d-5c84b1d2bd3d.png)

**Additional context**

**Comment by LonelyCpp** [comment]
Hi, there are already issues related to this with some possible workarounds - have a look #103, #82

**Comment by LonelyCpp** [comment]
If you have any ideas on how we can overcome this, you can share it here or even better - raise a PR 🙂

**Comment by Saad9624** [comment]
facing same issue while scrolling the popups appear and there is no way to disable this

**Comment by josegiufrida** [comment]
I put iframe video inside a carousel (react-native-snap-carousel). Its works fine but when I slide and go back the iframe opens the menu automatically.

**Comment by yogesh-jgu** [comment]
Facing the same issue while scrolling the multiple Youtube Video List and Crash the App if the list of youtube increased? Is there any solution to tackle these issues

**Comment by Dkathayat** [comment]
Same issue not able to find how to disable the long press options every video on the recylerview at some point get those options

**Comment by MarufSharifi** [comment]
did any body find a proper solution for this problem?
