### ISSUE TITLE
Hide the Top Info Bar from Video

### ISSUE THREAD

**Issue by Malikkhoja** [LonelyCpp/react-native-youtube-iframe#11]
Hi @LonelyCpp,

I am looking for a way to hide the top video info bar from the video. I went through the docs and couldn't find a solution. Is there any way to hide the top info bar on both the platforms?

Can you please help?

Thanks in advance

**Comment by LonelyCpp** [comment]
Hi, @Malikkhoja 

If you are referring to the video title and channel picture on top on the video, youtube no longer allows it.

> The `showinfo` parameter, which indicates whether the player should display information like the video title and uploader before the video starts playing, is also being deprecated.  (...) The avatar being displayed is new behavior that will be consistent across all embedded players.

**Comment by Malikkhoja** [comment]
Hi @LonelyCpp ,

Thanks for the quick response. However can we at-least stop the view watchlist(3 dots more button) and share feature? The link doesn't mention anything about this.

Thanks,
Malik Khoja

**Comment by LonelyCpp** [comment]
The three dots menu (aka the kebab menu) is also part of the info bar. There is nothing in their API which achieves this either. 

There are hacks to manipulate the iframe, but most don't work (old api) or they violate the youtube terms and condition.

Can I ask why you need the share button removed?

**Comment by Malikkhoja** [comment]
Hi @LonelyCpp ,

We want to live stream the videos on youtube and we want the user viewing the video to be the genuine users. So hence we  want to prevent sharing the link of the video.

Any possibility that we can prevent this?

Thanks for your help and quick responses. Really appreciated

**Comment by LonelyCpp** [comment]
I believe this won't be possible in other youtube libraries as well. As far as the library is concerned, this feature will be out of scope (at least till youtube disallows it). 

I will let you know here if I fond anything in the future.

---

A solution you can try, is to place a transparent touchable(touchablewithoutfeedback) positioned absolutely over the youtube player. This will prevent the user from interacting with the player. 

But this would mean you have to implement the video controls (play, pause, skip) on your own using the function available in the library.

**Comment by Malikkhoja** [comment]
@LonelyCpp  Thanks a lot for your suggestions :)

**Comment by subhashbrillmark** [comment]
@Malikkhoja The trick you can try is try to stop video on load which is somehting like this:-
![image](https://user-images.githubusercontent.com/45481188/109294019-a8d33f00-7852-11eb-8e92-fda603bffc40.png)
