### ISSUE TITLE
ios dimensions issue

### ISSUE THREAD

**Issue by LonelyCpp** [LonelyCpp/react-native-youtube-iframe#112]
Hi @LonelyCpp , its working great! I have however noticed one bug on iOS as soon as i shifted to this new package. Its as follows:
When your iOS device is on portrait > play the video while on portrait > hit the fullscreen button while on portrait > Now turn your device to landscape while on fullscreen.

At this point the DImensions API and useWindowDimensions from react native shows the opposite values for width. Meaning shorter width for landscape while larger width values on portrait (they basically get interchanged, landscape width is shown while on potrait while potrait width is shown on landscape). This however fixes when i exit from fullscreen and it behaves normally.

Can you look into this issue? We heavily depend on the screen width to make this responsive for portrait and landscape mode. And the issue is only on iOS. On android it works normally. It also behaves normally on 1.4.1. The issue only comes with this new package. Would really appreciate if you could look into this issue!

_Originally posted by @Priiyam in https://github.com/LonelyCpp/react-native-youtube-iframe/issues/98#issuecomment-786506082_

**Comment by LonelyCpp** [comment]
Hey @Priiyam I've moved your issue here to track it separately.

It's rather strange that the `useWindowDimensions ` started to behave differently in the new branch. i'll check this and let you know

**Comment by Priiyam** [comment]
@LonelyCpp thanks for the prompt response, much appreciated. Let me know if if you want my help in replicating the problem.

**Comment by LonelyCpp** [comment]
Hey, I tried to reproduce this on the ios emulator, I can't seem to get it right 

`useWindowDimensions()` don't react at all if I rotate the emulator during fullscreen video
