### ISSUE TITLE
Some videos not start playing with "An error occured." error

### ISSUE THREAD

**Issue by TTATPuOT** [LonelyCpp/react-native-youtube-iframe#116]
Somtimes, random videos did not plating. For example: https://www.youtube.com/watch?v=vZaIZgkCcXQ
If i make a code like
```jsx
<YoutubeIframe height={250} videoId="vZaIZgkCcXQ" />
```
I will have a empty black block with play button. And then, if i click on play, i have a black screen.
Player after scene loaded:
![image](https://user-images.githubusercontent.com/13170867/110796621-fb244f00-8299-11eb-84e9-47a4452a8a06.png)
And player after clicking on play:
![image](https://user-images.githubusercontent.com/13170867/110796655-037c8a00-829a-11eb-879f-8edf776ac1c7.png)

I have test it only on android.

 - Device: Android Pixel 2 Emulator/Galaxy S10, Android 11/10
 - `react-native-youtube-iframe` version: 1.4.1
 - `react-native-webview` version: 11.2.3
 - `Expo` verison [if using expo]: without Expo

**Comment by LonelyCpp** [comment]
Add an [`onError`](https://lonelycpp.github.io/react-native-youtube-iframe/component-props#onerror) callback to the player to see what error it is.

If the error is `embed_not_allowed`,  try the solution mentioned here -  https://github.com/LonelyCpp/react-native-youtube-iframe/issues/98#issuecomment-778005547

**Comment by TTATPuOT** [comment]
@LonelyCpp yes it is.
But if i create iframe in browser, its works: https://codesandbox.io/s/youtube-iframe-7boq0

**Comment by LonelyCpp** [comment]
yes this is a known issue. The library renders the iframe sourced from raw HTML generated on the go. This mean that the webview will have no origin URL set which leads to youtube throwing this error. (this only affects videos that have been set with `no embed` by the creators)

I'm working on publishing the fix soon 😄 

Meanwhile you can still use the code from `remote-source` - more info here https://github.com/LonelyCpp/react-native-youtube-iframe/issues/98#issuecomment-778005547 

Closing this (discuss in #98 for more)
