### ISSUE TITLE
Webview is crashing app on android 10 devices

### ISSUE THREAD

**Issue by Nimbo1999** [LonelyCpp/react-native-youtube-iframe#117]
**Describe the bug**
On Android 10 devices I am facing a crash when changing the screen to a component that doesn't has the YoutubeIframe from a screen that has. I though the problem it was with react-navigation library. But I found that the problem is with the react-native-webview library, which react-native-youtube-iframe uses it as a dependency. When looking for possible problems, we found this [comment](https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-639833153) talking about how to solve the crash problem in the web-view.

**To Reproduce**
Go to a screen that mounts the YoutubeIframe, after components fetch the video and be ready to play, navigate to other page with navigation.navigate(), of react-navigation. When you click a button or trigger some event that call this method the app will crash.

**Expected behavior**
It is expected to navigate to the other page.

**Screenshots**
none.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J8
 - OS + version: Android 10
 - `react-native-youtube-iframe` 1.4.1
 - `react-native-webview` 10.7.0

**Comment by LonelyCpp** [comment]
Yes this is a known issue from react native webview.

 Solutions -  #101 or #110
