### ISSUE TITLE
Disable interactiviy.

### ISSUE THREAD

**Issue by CyberCyclone** [LonelyCpp/react-native-youtube-iframe#120]
Is there a way to disable the interactivity? I'm using this in app for a TV and using the navigation allows you to interact with the iFrame. I want to disable this so that the events don't leak into it otherwise weird things start to happen and I lose control of the iFrame since elements inside are being clicked and can't be closed (since there's no pointer).

I've tried the below but it doesn't do anything:

```
View pointerEvents="none">
	<YoutubePlayer
		pointerEvents="none"
		height={"100%"}
		play={!paused}
		videoId={source}
		onChangeState={onStateChange}
	/>
</View>
```

Thanks!

**Comment by LonelyCpp** [comment]
have you tried wrapping the youtube player with a `<TouchableWithoutFeedback>` ?

**Comment by CyberCyclone** [comment]
Thanks for getting back so quick. I tried ```<TouchableWithoutFeedback>``` however that just masks that it's focused. Underneath it still is selected stuff. I've finally figured it out without needing to alter the package. The ```<Pressable>``` intercepts the interaction and stops it from reaching the below views.

```
<Pressable 
// Keep onPress here to catch interactions. We don't want anything getting to the YouTube iFrame.
onPress={() => {
	console.log("Pressed....");
}}
>
        <YoutubePlayer
	        pointerEvents="none"
	        height={"100%"}
	        play={!paused}
	        videoId={source}
	        onChangeState={onStateChange}
        />
</Pressable>
```

**Comment by hkar19** [comment]
btw it will still catch `onLongPress`. So i think the `Pressable` component needs to be given all press event an empty function
