### ISSUE TITLE
Allow overriding of URL

### ISSUE THREAD

**Issue by CyberCyclone** [LonelyCpp/react-native-youtube-iframe#121]
We're currently using this URL to disable elements on the YouTube element. I was wondering if it was possible to do the same by passing a full URL so we can use this: https://www.youtube-nocookie.com/ (which disable some functions).

```
<video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" src="blob:https://www.youtube-nocookie.com/b90f1eee-f50e-4144-8b14-7bfc9512f780" style="width: 413px; height: 250px; left: 0px; top: 0px;"></video>
```

Thanks!

**Comment by LonelyCpp** [comment]
you can see the source for the HTML here - https://github.com/LonelyCpp/react-native-youtube-iframe/blob/master/iframe.html

do you want this URL to be customizable? 
https://github.com/LonelyCpp/react-native-youtube-iframe/blob/f126b6f20f65e2abb6a2351341c63a2d8d5567a8/iframe.html#L70
