### ISSUE TITLE
why ios close button onChangeState = paused? 

### ISSUE THREAD

**Issue by toonlab01** [LonelyCpp/react-native-youtube-iframe#122]
![49785EE8-A847-4CD8-9DCC-CA651524F72E 사본](https://user-images.githubusercontent.com/80499674/112758100-8d14b180-9027-11eb-919e-9c9eb31d9009.png)

import Modal from 'react-native-modal';
import YoutubePlayer from "react-native-youtube-iframe";

          <Modal
            isVisible={video}
            onBackdropPress={ closeVideo }
            style={{
                margin: 0,
                flex:1,
                justifyContent: 'center',
                alignItems: 'center'
            }}
            coverScreen={false}
            backdropOpacity={1}
            >
        <YoutubePlayer
        width={Platform.OS === "ios" ? 'auto' : Constants.WINDOW_WIDTH}
        height={Platform.OS === "ios" ? 'auto' : Constants.WINDOW_HEIGHT}
        play={video}
        onFullScreenChange={onFullScreenChange}
        videoId={id_name}
        initialPlayerParams={{ cc_lang_pref: 'us', showClosedCaptions: true }}
        webViewProps={{
            injectedJavaScript: `
              var element = document.getElementsByClassName('container')[0];
              element.style.position = 'unset';
              element.style.paddingBottom = 'unset';
              true;
            `,
            allowsInlineMediaPlayback: false,
            onLoadStart :()=>{
                setLoad2(true);
            },
            onLoad : ()=>{
                setLoad2(false);
            }
          }}
        // prevent aspect ratio au
        onChangeState={(data)=>{
            if(data=='paused'){
                // closeVideo();
            }else if(data ='unstarted'){
                setLoad2(false);
            }else if(data = 'ended'){
                setLoad2(false);
            }
        }}
        forceAndroidAutoplay={Platform.OS === 'android'}
      />
        {  
             load2 == true  ? <UIActivityIndicator
            style={{
            flex: 1,
            zIndex:1000,
            alignItems: 'center',
            position: 'absolute',
            justifyContent: 'center' }}
            size={40} count={10}
            color='rgb(161,201,138)'
            />   : null
      }
        </Modal> 
![B795FD50-8E9F-4C0A-B49A-D5542F4E66EA](https://user-images.githubusercontent.com/80499674/112758207-00b6be80-9028-11eb-88d6-201be0309308.png)

I want the modal to close as well when the close button is pressed, but onChangeState is paused and this is also paused. How to close the modal? How do I modify the source to make the YouTube popup appear when you click the thumbnail image, and close the YouTube popup like a modal when you click the close button?

**Comment by LonelyCpp** [comment]
unfortunately there's no way to detect fullscreen enter / exit on ios. there's an issue already here - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/45
