### ISSUE TITLE
Library is logging requests

### ISSUE THREAD

**Issue by tomparkp** [LonelyCpp/react-native-youtube-iframe#126]
I noticed the library is now logging to the console, probably due to this line: https://github.com/LonelyCpp/react-native-youtube-iframe/commit/64591eb633797ce963c3944dfc7a30ca1ac0422d#diff-a604c7d6c91b379032daac98fc02887b0dae63b7dbd1d371322575e80f37da0bR226

I generally like to keep my logs clean except for error cases so it would be nice if this was removed or optional

<img width="460" alt="CleanShot 2021-03-31 at 23 21 52@2x" src="https://user-images.githubusercontent.com/2266762/113251895-e96e1000-9277-11eb-9bad-896b8cfcf951.png">

**Comment by LonelyCpp** [comment]
hey sorry. missed this console.log.
Fixed here - https://github.com/LonelyCpp/react-native-youtube-iframe/commit/2e953c94244bf349f377fd7f59781c83395ca2b2

Available in `v2.0.1`
