### ISSUE TITLE
player seekTo function not working in onReady callback?

### ISSUE THREAD

**Issue by davidhouse2003** [LonelyCpp/react-native-youtube-iframe#128]
**Describe the bug**
When the video is loaded I would like to start playing the video at some time not at the start of the video using the player seekto function. But for some reason it doesn't work and always play the video at the start of video.

**To Reproduce**
```javascript
import React, {useCallback, useRef } from "react";
import {View } from "react-native";
import YoutubePlayer from "react-native-youtube-iframe";

export default function App() {
  const playerRef: any = useRef();


  const onPlayerReady = useCallback(() => {
    playerRef.current?.seekTo("30");
  }, []);

  return (
    <View>
      <YoutubePlayer
         ref={playerRef} 
        height={300}
        play={false}
        videoId={"DC471a9qrU4"}
        onReady={onPlayerReady}
      />
   
    </View>
  );
}
```

**Expected behavior**
Video current time should be at 30 sec of video.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020 & Pixel 3
 - OS: iOS 14.4.2 & Android Version 11
 - `react-native-youtube-iframe` 2.0.1 
 - `react-native-webview` 11.0.0
 - `Expo` verison 40.0.0
 

**Additional context**

**Comment by maltz** [comment]
Try this and I think it will work.
`play={true}` (initial props)

**Comment by davidhouse2003** [comment]
It still doesn't work for me. The video plays but starts at time 0s instead of the 30s set by the seekTo.

**Comment by LonelyCpp** [comment]
`onReady` only signifies that the _player_ has loaded but and not the video. You must make sure that the video has actually finished buffering content for seek to work else the player will not know the video length before the video loads.

Try using the `onChangeState` callback to listen for "playing" before calling seek.

```jsx
const ref = useRef(); // player ref
const seekFlag = useRef(true); // a flag to prevent calling seek after calling it for the first time

<YoutubePlayer
  play={true}
  ref={ref}
  height={300}
  videoId={"vZaIZgkCcXQ"}
  
  onChangeState={(state) => {
    if (state === "playing" && seekFlag.current) {
      ref.current?.seekTo(30, true);
      seekFlag.current = false;
    }
  }}
/>
```

**Comment by davidhouse2003** [comment]
Wow thanks so much for the explanation and  code tip. It worked perfectly!

**Comment by LonelyCpp** [comment]
There's a better way to achieve this particular use-case with `start` in `initialPlayerParams`. [docs](https://lonelycpp.github.io/react-native-youtube-iframe/component-props#initialplayerparams)

```jsx
<YoutubePlayer
  ref={ref}
  play={true} 
  videoId={"vZaIZgkCcXQ"}
  initialPlayerParams={{ start: 30 }} // start video at a timestamp
/>
```
