### ISSUE TITLE
Version 2 may break with Expo managed apps

### ISSUE THREAD

**Issue by gianlucadifrancesco** [LonelyCpp/react-native-youtube-iframe#129]
Latest version of `react-native-youtube-iframe` (v2) seems incompatible with Expo.
The problem is the version of React: v17 is required by a peer dependency, but latest Expo (40) still uses React v16.

**To Reproduce**
Just run **`npm install react-native-youtube-iframe`** (or `expo install ...`) in an **Expo** managed app (I'm using Expo 40).
This error will be shown:
```
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-youtube-iframe@2.0.1
npm ERR!   node_modules/react-native-youtube-iframe
npm ERR!     react-native-youtube-iframe@"2.0.1" from the root project
npm ERR!   1 more (react-native)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=17.0.1" from react-native-web@0.15.6
npm ERR! node_modules/react-native-web
npm ERR!   peer react-native-web@"*" from react-native-web-webview@1.0.2
npm ERR!   node_modules/react-native-web-webview
npm ERR!     peer react-native-web-webview@">=1.0.2" from react-native-youtube-iframe@2.0.1
npm ERR!     node_modules/react-native-youtube-iframe
npm ERR!       react-native-youtube-iframe@"2.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
(This line in particular: **`peer react@">=17.0.1" from react-native-web@0.15.6`**)

The next version of Expo (41) will still use React v16 (RN v0.63) 😕.
Is there a way to use the `react-native-youtube-iframe` v2 in Expo without having to wait for Expo 42 (React v17)?

Thanks in advance!

**Comment by LonelyCpp** [comment]
* `react-native-web-webview` has a dependency on [react-native-web `"^0.13.4"`](https://github.com/react-native-web-community/react-native-web-webview/blob/master/package.json) 
* react 17 is only required on [react-native-web `v0.15+`](https://github.com/necolas/react-native-web/releases/tag/0.15.0)

If you don't use react native web, you can simply ignore the peer dependency. 

If you do use it - then install a version of react-native-web prior to v0.15 (`0.14.13` seems to be the the one just before 0.15)

**Comment by gianlucadifrancesco** [comment]
@LonelyCpp Perfect, I installed with `--force` and I confirm it works, ignoring the `react-native-web` dependency (in my case I don't use it).
Thank you!
