### ISSUE TITLE
iFrame padding/margin cannot be removed?

### ISSUE THREAD

**Issue by bastianspirek** [LonelyCpp/react-native-youtube-iframe#13]
I am trying to display the player with a width of 100%, however I am not able to remove the margin/padding completely. I tried using width={"100%"} and webViewStyle={{ marginHorizontal: 0, paddingHorizontal: 0}} however there will always be a white space around it. Is there anything else that I can change? I am not sure where this space is coming from.

**Comment by LonelyCpp** [comment]
Hey! Can I have a screenshot how of it looks on your device?

**Comment by bastianspirek** [comment]
![WhatsApp Image 2020-04-09 at 18 50 54](https://user-images.githubusercontent.com/7038550/78920066-23586c00-7a93-11ea-9e0a-4c2356a92d76.jpeg)
Of course, there you go.

**Comment by LonelyCpp** [comment]
hmm, weird. I put in some CSS for the player to always maintain aspect ratio, which is causing the problem. I'll fix it with a patch update. 

Thanks for raising the issue. I'll let you know when I'm done

**Comment by LonelyCpp** [comment]
Hey, can you try adding this - 

```
       webViewProps={{
          injectedJavaScript: `
          var element = document.getElementsByClassName('container')[0];
          element.style.position = 'unset';
          true;
          `,
        }}
```

If you make sure the container expands to full width, the video player also will match the parent. (but it wont preserve aspect ratio)

**Comment by bulby97** [comment]
The issue is with the body, it has a margin and padding by default.

**Comment by LonelyCpp** [comment]
Hi @bulby97 

If you see the html [here](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/aceeac41f70d004abd63da0fd66a9a3ccba1792b/src/PlayerScripts.js#L64), the container has the following style - 

```
  .container {
        position: relative;
        width: 100%;
        height: 0;
        padding-bottom: 56.25%;
      }
```

This causes the player to fit appropriately in the view port, maintaining aspect ratio at all times. It makes sure the player doesn't overflow if the containing view is less than 400px in width. Detailed explanation [here](https://css-tricks.com/fluid-width-video/). 
Removing the `position` attribute seems do the trick here. (player get a full 100% width but aspect ratio is not maintained)

**Comment by bastianspirek** [comment]
@LonelyCpp 
Thanks, the JS injection does the trick, however I feel it's not the most elegant way, as you can even see the player loading and then adjusting the size.

But @bulby97 is right, the HTML body usually has a margin of 8px, maybe it would help to just add 
body { margin: 0px, padding: 0px; } to the styles?

https://stackoverflow.com/a/13128048/6225257

**Comment by LonelyCpp** [comment]
> the HTML body usually has a margin of 8px

TIL
I will try that, thanks :)

**Comment by bulby97** [comment]
I downloaded your code on local to be able to use it and modify it. Thank you for you awesome work.

If I may give some advices:

- Put the default width / height of the webview to 16/9, so that you doesn't need to provide width and height to the webview if not needed.

- There is a screen flickering, because the iFrame take some time to load. I would recommend to maybe add a placeholder. Loading component, or alt text, in case there is no connection. In my case, I added the following:
![image](https://user-images.githubusercontent.com/3509412/78981451-10699880-7b74-11ea-8e82-df5fca772e27.png)

**Comment by LonelyCpp** [comment]
Hey @bulby97,

I've left out the placeholder in favour or the `onReady` and `onError` callback. This allows a dev to put their own loader / placeholder / error message. This keeps the library clean and customizable. 

I recommend you to handle the placeholder outside the library (maybe an opaque view over the player till `onReady` is fired). What do you think?

**Comment by LonelyCpp** [comment]
Fixed!

**Comment by bulby97** [comment]
> Hey @bulby97,
> 
> I've left out the placeholder in favour or the `onReady` and `onError` callback. This allows a dev to put their own loader / placeholder / error message. This keeps the library clean and customizable.
> 
> I recommend you to handle the placeholder outside the library (maybe an opaque view over the player till `onReady` is fired, then fade it out using `Animated`).
> What do you think?

Actually you're right mate ! Thanks.

**Comment by arfa123** [comment]
> Hey, can you try adding this -
> 
> ```
>        webViewProps={{
>           injectedJavaScript: `
>             var element = document.getElementsByClassName('container')[0];
>             element.style.position = 'unset';
>             true;
>           `,
>         }}
> ```
> 
> If you make sure the container expands to full width, the video player also will match the parent. (but it wont preserve aspect ratio)

Thanks, you save my time

**Comment by LonelyCpp** [comment]
here's a snippet to achieve this - 

```js
import React, { useEffect, useState } from "react";
import { Dimensions } from "react-native";
import { View } from "react-native";
import YoutubePlayer from "react-native-youtube-iframe";

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export default function App() {
  return (
    // rotate by 90 deg for horizontal video
    <View style={{ transform: [{ rotate: "90deg" }] }}>
      <YoutubePlayer
        videoId={"XSqi5s3rfqk"}
        // video height -> screen width
        height={SCREEN_WIDTH}
        // video width -> screen height
        width={SCREEN_HEIGHT}
        // prevent aspect ratio auto sizing
        webViewProps={{
          injectedJavaScript: `
            var element = document.getElementsByClassName('container')[0];
            element.style.position = 'unset';
            element.style.paddingBottom = 'unset';
            true;
          `,
        }}
      />
    </View>
  );
}

```

**Comment by rameziophobia** [comment]
> Hi @bulby97
> 
> If you see the html [here](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/aceeac41f70d004abd63da0fd66a9a3ccba1792b/src/PlayerScripts.js#L64), the container has the following style -
> 
> ```
>   .container {
>         position: relative;
>         width: 100%;
>         height: 0;
>         padding-bottom: 56.25%;
>       }
> ```
> 
> This causes the player to fit appropriately in the view port, maintaining aspect ratio at all times. It makes sure the player doesn't overflow if the containing view is less than 400px in width. Detailed explanation [here](https://css-tricks.com/fluid-width-video/).
> Removing the `position` attribute seems do the trick here. (player get a full 100% width but aspect ratio is not maintained)

this works but causes a bug where returning from fullscreen ruins the video

**Comment by SufianBabri** [comment]
Thanks to @bastianspirek for [their comment](https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611924465), I am wrapping my `<iframe>` in a `<body>` like this:

```
<WebView
        source={{
    	              html: `<body style="margin: 0;">
    	                       <iframe
    	                           style="border-width: 0;"
    	                           width='100%'
    	                           height='100%'
    	                           src='${pageUrl}' />
    	                     </body>`
    	        }}
/>
```

The `body`'s style removes the unwanted 8px spacing, and the `iframe`'s style removes the border around itself. Now the `iframe` doesn't seem to have any spaces around.

**Comment by nguoidungg** [comment]
> Hi @bulby97
> 
> If you see the html [here](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/aceeac41f70d004abd63da0fd66a9a3ccba1792b/src/PlayerScripts.js#L64), the container has the following style -
> 
> ```
>   .container {
>         position: relative;
>         width: 100%;
>         height: 0;
>         padding-bottom: 56.25%;
>       }
> ```
> 
> This causes the player to fit appropriately in the view port, maintaining aspect ratio at all times. It makes sure the player doesn't overflow if the containing view is less than 400px in width. Detailed explanation [here](https://css-tricks.com/fluid-width-video/). Removing the `position` attribute seems do the trick here. (player get a full 100% width but aspect ratio is not maintained)

do you have any props? i have to edit the source code?
