### ISSUE TITLE
Play Store Rejection

### ISSUE THREAD

**Issue by pairohit305** [LonelyCpp/react-native-youtube-iframe#130]
**Describe the bug**
My app got rejected! and google send me this screenshot

I am not sure what is the problem ??
Youtube is not the core function I have 1 tab for youtube video
I know the youtube  vdo shd stops when the app goes to background (Even thou I am not using apostate to pause but react-native-ifrae-youtube stop automatically when app goes to background ) but this lib stop the vdo when app goes to background

**Screenshots**
![com creatorcodesupercell-InAppExperience-63](https://user-images.githubusercontent.com/36040318/115111440-07d54a80-9f9e-11eb-82fa-9ec72ea68529.png)

**Comment by pairohit305** [comment]
Is it because I have that fullscreen icon on the right side ??

**Comment by pairohit305** [comment]
![WhatsApp Image 2021-04-17 at 17 25 06](https://user-images.githubusercontent.com/36040318/115112377-db6ffd00-9fa2-11eb-834c-a480231bfa4b.jpeg)

**Comment by LonelyCpp** [comment]
I'd the fullscreen icon rendered by your app?? If it's by the youtube player itself - then it's not the issue.

Even though the video automatically stops when the app goes to background, it is essential that you add app-state handling as well.

We've had past rejections on the play store as well, and it's solved by adding AppState.

**Comment by pairohit305** [comment]
Not that fullscreen icon i added

**Comment by pairohit305** [comment]
Ohh really then I will add that apostate functionality

**Comment by pairohit305** [comment]
![Inkedcom creatorcodesupercell-InAppExperience-63_LI](https://user-images.githubusercontent.com/36040318/115114238-cba8e680-9fab-11eb-8f8b-8f8a80ecc4d1.jpg)
I added this fullscreen icon

**Comment by LonelyCpp** [comment]
Oh in this case, it does violate their ToS.

https://developers.google.com/youtube/terms/required-minimum-functionality#overlays-and-frames

> You must not display overlays, frames, or other visual elements in front of any part of a YouTube embedded player, including player controls. Similarly, you must not use overlays, frames or other visual elements to obscure any part of an embedded player, including player controls.

General rule of thumb is to not have any opaque UI elements on top of the player. You'll have to move the fullscreen button outside the player bounds

**Comment by LonelyCpp** [comment]
A quick snippet of how I use app-state in my apps: 

```javascript
import { useAppState } from '@react-native-community/hooks'

const currentAppState = useAppState()

if(currentAppState !== 'active') {

  return null;

} else {

  return <YoutubePlater ... />

}
```

**Comment by pairohit305** [comment]
Also what about this one 
![WhatsApp Image 2021-04-17 at 18 44 27](https://user-images.githubusercontent.com/36040318/115114454-2262f000-9fad-11eb-9ebd-cfa02a9c49e0.jpeg)

I have yellow back button 

Will this also violate ?? It just outside the player

**Comment by LonelyCpp** [comment]
ya just make sure that the back arrow never overlaps with the player.

**Comment by pairohit305** [comment]
Yes that yellow icon will never overlay But thanks for the help 💙 Will close this issue as soon as the app gets accepted

**Comment by pairohit305** [comment]
Hey, one more question from your implement when the app goes to the background u are completely destroying the youtube complement which means it lost the state What if I just pause and not destroy the whole component?

**Comment by LonelyCpp** [comment]
hey yeah, just pausing the playback should work too. 

one more thing to consider - the border radius also technically overs a tiny part of the player.

**Comment by pairohit305** [comment]
Yes that's y I removed the border-radius aswell

**Comment by LonelyCpp** [comment]
Hey did the app get accepted?

**Comment by pairohit305** [comment]
Yep, It got accepted after Removing the border radius and that Icon. Also, I don't think that the app state method is necessary because ur lib stop automatically when the app goes to the background 

I can confirm that app state is not necessary because I have one area in which I have not implemented the app state still my app was accepted

**Comment by vegerot12** [comment]
Did you face rejection in appStore as well or it was in playStore only. As i can see the fullScreen callback works in android so im thinking of adding overlay on iOS alone to handle the fullScreen callback , please confirm if anyone faced rejection for using overlay in appStore, thanks in advance.  @pairohit305 @LonelyCpp
