### ISSUE TITLE
initialPlayerParams not working [rel] [modestbranding]

### ISSUE THREAD

**Issue by aman-technyx** [LonelyCpp/react-native-youtube-iframe#131]
**HELP ME OUT**

on react native project initialPlayerParams is not working properly, i cant be able to disable related videos and also youtube logo is also coming my code is this: 

 <YoutubePlayer
        ref={videoRef}
        webViewStyle={[styles.video]}
        // initialPlayerParams={{rel: 0 , modestbranding: 1, iv_load_policy : 0 ,controls: 0, showClosedCaptions: false}}
        initialPlayerParams={{ rel: false, loop: true, controls: false, modestbranding: false }}
        height={300}
        play={state.play}
        videoId={"iee2TATGMyI"}
        contentScale={0}
    />

**Smartphone (please complete the following information):**
 - Device: [e.g. pixel 1]
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` 2.0.1"
 - `react-native-webview` 11.4.0

**Comment by LonelyCpp** [comment]
> i cant be able to disable related videos

Disabling related videos is not possible (it used to be supported, but youtube has removed this feature). 

If the rel parameter is set to 0, related videos will come from the same channel as the video that was just played.

---

> youtube logo is also coming

The logo is only removed from the player "control bar".  Can you add a screenshot for reference?
