### ISSUE TITLE
Getting error : UNAUTHORIZED_OVERLAY  target: 8233

### ISSUE THREAD

**Issue by raazatul7** [LonelyCpp/react-native-youtube-iframe#134]
**Describe the bug**
Getting error: UNAUTHORIZED_OVERLAY  target: 8233 on Android only.

**To Reproduce**
Install and play video.
Using the latest version 2.0.1

**Expected behavior**
It should play video

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi 7s
 - OS + version: Android 10
 - `react-native-youtube-iframe` 2.0.1 
 - `react-native-webview` 11.4.2

**Additional context**
Video plays for a second and then throws an error - UNAUTHORIZED_OVERLAY again when I tap play it starts for a second then the same error.

**Comment by LonelyCpp** [comment]
How exactly are you getting this error? Logs would be helpful.

Are you sure you're not using `react-Native-youtube`?? since that library infamously had this error and iframe was created to solve it?

**Comment by raazatul7** [comment]
> How exactly are you getting this error? Logs would be helpful.
> 
> Are you sure you're not using `react-Native-youtube`?? since that library infamously had this error and iframe was created to solve it

You're right
Sorry for bothering you.
Thanks
