### ISSUE TITLE
"Hello world" in remote-source branch

### ISSUE THREAD

**Issue by TTATPuOT** [LonelyCpp/react-native-youtube-iframe#135]
Sometimes, if i use `remote-source` branch for no-embed videos, i have an error:
![image](https://user-images.githubusercontent.com/13170867/115575881-6a9b4e80-a2dc-11eb-9957-c33ab8ddeab7.png)

For example: https://www.youtube.com/watch?v=189laEQTBxs

 - Device: any
 - OS + version: any
 - `react-native-youtube-iframe` version: https://github.com/LonelyCpp/react-native-youtube-iframe#remote-source
 - `react-native-webview` version: 11.2.3
 - Without Expo

**Comment by LonelyCpp** [comment]
Damn. This explains all the weird page loads i've been seeing on https://lonelycpp.github.io/

Please use the latest version on npm (`v2.0.1`).

**Comment by TTATPuOT** [comment]
> Damn. This explains all the weird page loads i've been seeing on https://lonelycpp.github.io/
> 
> Please use the latest version on npm (`v2.0.1`).

Yes, `2.0.1` works fine. Thank you for quick response.
