### ISSUE TITLE
react-native-youtube-iframe does not support vertical videos

### ISSUE THREAD

**Issue by oussamakenzup** [LonelyCpp/react-native-youtube-iframe#136]
I'm using the package correctly and it is working great with auto play, but we have a vertical video we want to use that introduces our app.

Using a vertical video works well in full screen, but in the iframe you cannot make it vertical, changing the height and width to a vertical aspect ration just make the webView handling the iframe taller.

```
      <YoutubePlayer
        height={600}
        width={350}
        play={playing}
        videoId={'yabDCV4ccQs'}
        onChangeState={onStateChange}
      />
```

There is no way to support vertical videos in the docs either.

**Comment by LonelyCpp** [comment]
yeah, the player defaults to a 16:9 aspect ratio. 

try https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123 to expand the player to any height

**Comment by oussamakenzup** [comment]
Thank you so much 🙏, I suggest we add this as a prop like isVertical to the library. It is working well.

**Comment by LonelyCpp** [comment]
definitely. I'll update in #64 when it's done 😄
