### ISSUE TITLE
PlayList doesn't seem to work

### ISSUE THREAD

**Issue by ProjectKB** [LonelyCpp/react-native-youtube-iframe#141]
**Describe the bug**
playList props doesn't seem to work.

**Screenshots**
<img width="544" alt="Screenshot 2021-05-04 at 21 36 22" src="https://user-images.githubusercontent.com/36883642/117060444-39317280-ad21-11eb-9d15-8865e0311326.png">
<img width="451" alt="Screenshot 2021-05-04 at 21 36 35" src="https://user-images.githubusercontent.com/36883642/117060451-3c2c6300-ad21-11eb-9ddb-15b9ead31156.png">

**Smartphone (please complete the following information):**
 - Device: Android Pixel_2_API_29(AVD) and SM-J600FN - 10
 - OS + version: Android 10
 - `react-native-youtube-iframe` version 2.0.1
 - `react-native-webview` version 11.4.3

**Comment by LonelyCpp** [comment]
fixed in `v2.1.0` 🥳 

reopen this if you still face the same problem

**Comment by ProjectKB** [comment]
Works perfectly, thanks!
