### ISSUE TITLE
Android : Border radius doesn't work 

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [LonelyCpp/react-native-youtube-iframe#147]
**Describe the bug**
border radius doesn't work in Android 
**To Reproduce**
add the border radius using the below code : 

`
import YoutubePlayer from 'react-native-youtube-iframe';
  
 <YoutubePlayer
          height={200}
          play={false}
          controls={1}
          loop={false}
          onReady={() => {
            setIsReady(true);
          }}
          onProgress={() => {
            console.log('onProgress');
          }}
          fullscreen={false}
          onError={e => {
            setIsReady(true);
            console.log('Error youtube: ', e.error);
          }}
          videoId={props.videoId}
          webViewStyle={{borderRadius: 10}}
        />`
**Expected behavior**
border radius most be appeared 
**Screenshots**
![SSV](https://user-images.githubusercontent.com/65596246/120164020-cb367900-c202-11eb-9816-0eb9b845c513.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - OS + version: [e.g. Android 8 and Android 11]
 - `react-native-youtube-iframe` version : ^2.1.0 
 - `react-native-webview` version : ^11.6.2
 - `Expo` verison : not using 

**Additional context**
it is working on iOS , the issue only with android

**Comment by LonelyCpp** [comment]
Try overflow: 'hidden'

**Comment by LonelyCpp** [comment]
You can also just wrap the component with some border and overflow set to hidden (to avoid sending props directly to the webview)

P.S: if you are planning to publish this app, Google will not accept it since modifying the player in anyway is against the or ToS
