### ISSUE TITLE
Android background played is inactive while buffering.

### ISSUE THREAD

**Issue by aposto** [LonelyCpp/react-native-youtube-iframe#149]
**Describe the bug**
Video is played in the background state of the app .
Inactive the app in the background while buffering causes the video to play and sound. 
Always occurs when the app is inactive while buffering.

**To Reproduce**
1. iFrame play video.
2. Putting the app in the background while buffering.
3. The video plays and you hear sound.

**Expected behavior**
Stops video if it goes into background state during playback or buffering.

**Smartphone :**
 - Device: [Android*]
 - OS + version: [ Android 10]
 - `react-native-youtube-iframe` 2.1.0 
 - `react-native-webview` 11.6.2

**Comment by LonelyCpp** [comment]
Hey this library does not prevent background play. 

If you want to stop it, you can use [AppState](https://reactnative.dev/docs/appstate) to detect and stop background play
