### ISSUE TITLE
Support FullScreen Props.

### ISSUE THREAD

**Issue by aposto** [LonelyCpp/react-native-youtube-iframe#152]
I want to control the full screen mode from the outside (not Youtube GUI).
Please add property or method.
Is it possible?

**Comment by LonelyCpp** [comment]
this is currently not possible. 

The YouTube iframe APIs does not have such controls. [docs for reference](https://developers.google.com/youtube/iframe_api_reference)

If you find any such method, let me know

**Comment by aposto** [comment]
Could it be done in the following way?

https://github.com/LonelyCpp/react-native-youtube-iframe/blob/54f81db8b171e64483d53ba494149317da3a6146/src/PlayerScripts.js#L191
```
playsinline: props.fullscreen === true ? undefined : 1
```

**Comment by LonelyCpp** [comment]
hey Isorry for the late response. `playsinline` is a property of the player object itself. Changing it will reload the player (since the player object will be recreated)

**Comment by Anusha-Gurajapu** [comment]
@aposto did you find any solution for this ?

**Comment by aposto** [comment]
@Anusha-Gurajapu I'm using 'react-native-keep-awake'.

**Comment by aposto** [comment]
@Anusha-Gurajapu Currently, I am using the method of saving the section information during full screen and then playing the section again.

**Comment by Anusha-Gurajapu** [comment]
> @Anusha-Gurajapu Currently, I am using the method of saving the section information during full screen and then playing the section again.

Thanks for the response @aposto 

May I know how are you controlling the full screen mode from the outside (not Youtube GUI).

**Comment by Sakshisrivastava413** [comment]
any update on this feature request?
