### ISSUE TITLE
App chrashing when navigating to previous screen

### ISSUE THREAD

**Issue by kyle-belle** [LonelyCpp/react-native-youtube-iframe#154]
Hey.
I'm experiencing a pretty weird error which happen on my real device (OnePlus 7Pro - Android 10). I made a video to showcase the error as i don't know how to full describe with words:

[https://www.dropbox.com/s/e00tr8c4vhzdizm/21-06-11-19-34-10.mp4?dl=0](url)

it actually works fine on my emulator (which is either android 7 or 8) but not my real device.

and yes i'm 100% sure the youtube player is whats causing the crash because when i comment it out it starts working again.
anyways, i really hope someone can help me.

**Comment by LonelyCpp** [comment]
Hi, this is a known issue with react-navigation and rn-web-view. Fortunately we do have workarounds :)

* #101 
* #110 
* [original issue in rn-webview](https://github.com/react-native-webview/react-native-webview/issues/811)

**Comment by LonelyCpp** [comment]
you can read more about it in the documentation [here](https://github.com/LonelyCpp/react-native-youtube-iframe/blob/master/docs/navigation-crash.mdx)
