### ISSUE TITLE
Auto Height

### ISSUE THREAD

**Issue by Dineshi2419** [LonelyCpp/react-native-youtube-iframe#160]
HI,
I Widget work very smooth in both Andorid and iOS, but i want to have 100% width and Height as Auto, is it possible. Any work around kindly let me know.

**Comment by LeonidVeremchuk** [comment]
@Dineshi2419 
The standard aspect ratio for YouTube is 16:9

So you can calculate height, sample:
`import { Dimensions } from "react-native";
`
`const height = (Dimensions.get("window").width / 16) * 9;`
