### ISSUE TITLE
getYoutubeMeta call not returning anything

### ISSUE THREAD

**Issue by idoor88** [LonelyCpp/react-native-youtube-iframe#162]
I tried to call getYoutubeMeta as this:

import {getYoutubeMeta} from 'react-native-youtube-iframe';

getYoutubeMeta('sNhhvQGsMEc').then(meta => {
          console.log("getYoutubeMeta meta: ", meta);
          
        });
or:

let resultData = await getYoutubeMeta('sNhhvQGsMEc');
        console.log("getYoutubeMeta resultData: ", resultData);
       
Neither way worked, no results printed out and the call never came back, but the video can play with the player, I am using the most recent versions.
 

Smartphone:
 - Device: Android Phone Galaxy A30s
 - OS + version: Android 10 
    "react-native-webview": "^11.6.4",
    "react-native-youtube-iframe": "^2.1.0",
 - No expo
 "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by LonelyCpp** [comment]
works for me with 
```js
 getYoutubeMeta('sNhhvQGsMEc')
      .then((res) => console.log(res))
```

```json
Object {
  "author_name": "Kurzgesagt – In a Nutshell",
  "author_url": "https://www.youtube.com/c/inanutshell",
  "height": 113,
  "html": "<iframe width=\"200\" height=\"113\" src=\"https://www.youtube.com/embed/sNhhvQGsMEc?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>",
  "provider_name": "YouTube",
  "provider_url": "https://www.youtube.com/",
  "thumbnail_height": 360,
  "thumbnail_url": "https://i.ytimg.com/vi/sNhhvQGsMEc/hqdefault.jpg",
  "thumbnail_width": 480,
  "title": "The Fermi Paradox — Where Are All The Aliens? (1/2)",
  "type": "video",
  "version": "1.0",
  "width": 200,
}
```

**Comment by LonelyCpp** [comment]
you can examine the exact API call it makes here : https://github.com/LonelyCpp/react-native-youtube-iframe/blob/d87a576f24d884f74bb73938af18b43185bcf333/src/oEmbed.js#L57
