### ISSUE TITLE
change Quality of the video

### ISSUE THREAD

**Issue by Anusha1509** [LonelyCpp/react-native-youtube-iframe#163]
I would like to change Quality of the video. How can I do that. I hope we can do that similar to changing the playback rate. https://developers.google.com/youtube/iframe_api_reference#october-24,-2019 

Please, look into this asap. @LonelyCpp

**Comment by LonelyCpp** [comment]
The link that you provided itself says that

> The getPlaybackQuality, setPlaybackQuality, and getAvailableQualityLevels functions are **no longer supported**
