### ISSUE TITLE
Error while installing package react-native-youtube-iframe

### ISSUE THREAD

**Issue by affan00733** [LonelyCpp/react-native-youtube-iframe#168]
(base) affan@affans-MacBook-Air ecsDegreeM3IT % npm install --save react-native-youtube-iframe
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ecsdegreem3it@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-native-youtube-iframe@2.1.1
npm ERR!   node_modules/react-native-youtube-iframe
npm ERR!     react-native-youtube-iframe@"*" from the root project
npm ERR!   2 more (react-native, react-native-web)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=17.0.1" from react-native-web@0.17.1
npm ERR!   node_modules/react-native-web
npm ERR!     peer react-native-web@"*" from react-native-web-webview@1.0.2
npm ERR!     node_modules/react-native-web-webview
npm ERR!       peer react-native-web-webview@">=1.0.2" from react-native-youtube-iframe@2.1.1
npm ERR!       node_modules/react-native-youtube-iframe
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/affan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/affan/.npm/_logs/2021-07-24T02_04_52_348Z-debug.log
(base) affan@affans-MacBook-Air ecsDegreeM3IT %

**Comment by LonelyCpp** [comment]
Use yarn

Or with npm - `npm install --legacy-peer-deps `
