### ISSUE TITLE
allowWebViewZoom = {false} not working

### ISSUE THREAD

**Issue by tuladharjaa** [LonelyCpp/react-native-youtube-iframe#171]
<YouTubePlayer
          height={300}
          play={true}
          videoId={'E-51Kc42hoQ'}
          allowWebViewZoom={false}
/>

While pinching on the video it zooms in.

**Comment by LonelyCpp** [comment]
fixed! - https://github.com/LonelyCpp/react-native-youtube-iframe/commit/13965da99832e8f927c4f490b4bf8dbe1d9d5ad3

unless you're using a custom html source, you won't have to update anything :)
