### ISSUE TITLE
Placeholder before onReady?

### ISSUE THREAD

**Issue by ghiculescualexandru** [LonelyCpp/react-native-youtube-iframe#172]
Is there a way to display a message or a skeleton until the YoutubePlayer is ready?

I made a workaround:

```
  const [loading, setLoading] = useState(true);

  const onReady = useCallback(() => {
    setLoading(false);
  }, []);

  const onError = useCallback(() => {
    setLoading(false);
  }, []);

  return (
      <View style={containerStyle}>
        {loading ? <Placeholder /> : null}
        <YoutubePlayer
          height={loading ? 0 : 300}
          onReady={onReady}
          onError={onError}
        />
      </View>

```

If not, I think a 'Placeholder' prop to YoutubePlayer would be great.

**Comment by LonelyCpp** [comment]
Hey it's very simple to add a placeholder with the `onReady` callback (as you've used perfectly in the example)

The library can't assume the kind of a loading placeholder or error placeholder a user might want, and it adds complexity to make it customisable. 

So to keep this library light and maximise customisability, this particular feature is not implemented in the library itself.
