### ISSUE TITLE
Autoplay does not work upon videoId changes

### ISSUE THREAD

**Issue by hoangvvo** [LonelyCpp/react-native-youtube-iframe#176]
**Describe the bug**

If `videoId` is changed after the first render of `YoutubePlayer`, the video will not autoplay despite `play` prop being true

**To Reproduce**

https://snack.expo.dev/zeiphINXa

1. Click `Toggle Render` -> see that video is autoplayed.
2. Click `Switch video` -> video is no longer played
3. Click `Toggle Render` twice to unmount and remount component -> video is autoplayed

**Expected behavior**

Video should always be played or paused based on the `play` prop

I tested this on both Expo and bare React Native project.

**Smartphone (Expo):**
 - Device: n/a
 - OS + version: Android/iOS
 - `react-native-youtube-iframe` version 11.6.2
 - `react-native-webview` version ^2.1.1
 - `Expo` version 42.0.0

**Smartphone (Bare):**
 - Device: Poco X3 Pro
 - OS + version: Android 11
 - `react-native-youtube-iframe` version 11.6.2
 - `react-native-webview` version ^2.1.1
 - `Expo` version 42.0.0

Thank you.

**Comment by LonelyCpp** [comment]
hmm yes. 

A whole new js player instance is created when the videoId is changed. But the RN code was not taking this into consideration. 

this seems to have fixed it - https://github.com/LonelyCpp/react-native-youtube-iframe/commit/dad252aeb38403d5477520c522117febf9769e7a, but I couldn't fully test it. 

I'll release a patch version as soon as I test it for a bit :)

**Comment by hoangvvo** [comment]
Thanks for the response. I have a question though, why would we recreate the js player instead of just asking the existed player to call [player.loadVideoById](https://developers.google.com/youtube/iframe_api_reference#loadVideoById), possible via `injectJavaScript`?

**Comment by LonelyCpp** [comment]
@hoangvvo the fix is published in `v2.1.2`. let me know if it works :)

---

> call player.loadVideoById

yep, this is definitely a better way to do it. I've added this to a todo list of APIs to port in a future update!

(https://github.com/LonelyCpp/react-native-youtube-iframe/projects/3)

**Comment by hoangvvo** [comment]
> @hoangvvo the fix is published in `v2.1.2`. let me know if it works :)
> 
> ---
> 
> > call player.loadVideoById
> 
> yep, this is definitely a better way to do it. I've added this to a todo list of APIs to port in a future update!
> 
> (https://github.com/LonelyCpp/react-native-youtube-iframe/projects/3)

Awesome, I'd love to open a PR for that too if you don't mind

**Comment by LonelyCpp** [comment]
PRs are welcome! 💯

**Comment by hoangvvo** [comment]
@LonelyCpp I can confirm that the new version works! I will try to put together a PR some time soon for the discussed refactor though.

Thanks for the work!

**Comment by vishwadeepghimirezph** [comment]
Thank you @LonelyCpp and @hoangvvo. Issue is still there for iOS device. Could you please look into this in iOS? @LonelyCpp @hoangvvo

**Comment by LonelyCpp** [comment]
@vishwadeepghimirezph this was published with v2.2.0

try it out and let me know
