### ISSUE TITLE
The video restarts when a tabview, tab is selected 

### ISSUE THREAD

**Issue by aditechsachinc** [LonelyCpp/react-native-youtube-iframe#178]
I have a video embedded inside a scrollview with a  sibling TabView . Every time a Tab is selected, the video restarts. 
Below is the partial code:

`<ScrollView scrollEnabled={false}  keyboardShouldPersistTaps="handled">
      <SafeAreaView>
		<View>
			<YoutubePlayer
			  videoId = {url.split("=").pop()}
			  play
			  style={{ minHeight: videoheight, maxHeight: videoheight }}
			  onError={e => console.log('error while loading video :', e)}
			  fullscreen={false}
			  height = {videoheight}
			  onReady = {console.log('loaded video')}			
			/>
			
			style={{
			  top: 0,
			  height: 50,
			  width: '100%',
			  position: 'absolute',
			}}
		  />
		</View>
                <CardView>
          <View
            style={{
              fontFamily: "Helvetica Neue Medium",
              letter: "Normal",
              paddingBottom: 7,
              paddingTop: 10,
              paddingBottom: 10,
              paddingLeft: 20,
            }}
          >
            <Text
              style={{
                fontSize: 14,
                lineHeight: 14,
                color: "#0395E7",
              }}
            >
              {name}
            </Text>
          </View>
        </CardView>
        <View
          style={{
            minHeight: tabviewheight,
            maxHeight: tabviewheight,
            marginLeft: 5,
            marginRight: 5,
          }}
        >
          <TabView
            renderTabBar={(props) => <TabBar {...props} />}
            style={{
              flex: 1,
            }}
            navigationState={{ index, routes }}
            renderTabBar={renderTabBar}
            renderScene={renderScene}
            onIndexChange={setIndex}
          />
        </View>
      </SafeAreaView>
    </ScrollView>
  );
};`

Please let me know if anything is wrong. The same issue is not appearing for the expo-av Video player. ( we use that for other  video sources than Youtube)

**Comment by LonelyCpp** [comment]
This is too less context for me to say anything. 

Try creating a minimal RN app (or expo snack) that reproduces this issue.

**Comment by aditechsachinc** [comment]
The issue got resolved after I moved the youtube player component inline the main view, earlier it was a separate component
