### ISSUE TITLE
Video starts without image

### ISSUE THREAD

**Issue by fviazzi** [LonelyCpp/react-native-youtube-iframe#179]
I have a few videos on my app that were working perfectly, but now, when I hit play, the video starts without image (stays black). Sounds seems to be working fine.

Opening the video on youtube works.

Seems to affect just android. tested on samsung, pixel and xiaomi devices. Android studio emulator (Pixel 4 XL) is also failing.

react-native: 0.63.4
react-native-webview: 11.2.3
react-native-youtube-iframe: 2.1.1

**Comment by LonelyCpp** [comment]
can you show how you've used the component? it could be because of some props related to the underlying web view

**Comment by fviazzi** [comment]
Yes of course.

This is my component, media is an object with a `video` property (which is a YT video ID) and a `image` (the thumbnail).

As I said, is working on IOS and some Android devices (xiaomi mi 10t pro works, but redmi 7 and 9 don't)

```
// External Modules
import React from "react";
import { Image, TouchableOpacity, View } from "react-native";
import { AntDesign } from '@expo/vector-icons';
import YoutubePlayer from "react-native-youtube-iframe";

// Internal Modules
import Style from "./ExternalPlayerStyle.js";
import SpinnerIcon from "../SpinnerIcon/SpinnerIcon";

export default function ExternalPlayer({ media, provider = "youtube" }) {

  // Local state
  const [player, setPlayer] = React.useState({});
  const video               = React.useRef(null);

  React.useEffect(() => {

    setPlayer({
      ...media,
      loading: false,
      started: false,
      playing: false
    });

  }, [media]);

  const loadVideo = async () => {

    if (provider === 'youtube') {

      // Update UI
      setPlayer({
        ...player,
        loading: true,
        started: true
      });

      // Remove loader
      setTimeout(() => {
        setPlayer({
          ...player,
          loading: false,
          started: true,
          playing: true,
        });
      },1000);
    }
  }

  return (
    <View style={Style.container}>

        {/* Loading */}
        {
          player.loading ?

            <View style={Style.loading}>
              <SpinnerIcon
                style={Style.loadingIcon}
                name="spinner"
                loading={player.loading}
                duration={1200}
              />
            </View>

            : null
        }

        {/* Video */}
        <View
          style={ player.started ? Style.videoContainer : {display: "none"}}
        >

          {/* Video */}
          {
            provider === 'youtube' ?

              <YoutubePlayer
                play={player.playing}
                ref={video}
                height={200}
                videoId={player.video}
                onError={() => { }}
              />
            :
              null
          }
        </View>

        {/* Thumbnail */}
        {

          player.started ? null :

            <TouchableOpacity onPress={loadVideo}>
              <AntDesign style={Style.playIcon} name="play" />
              <Image source={{ uri: player.image }} style={Style.thumbnail} />
            </TouchableOpacity>
        }
    </View>
  )
}

```

**Comment by maestor** [comment]
We have same, it worked well at least yesterday morning, and today got same behaviour than issue opener (that some Androids show black screen but sounds worked, iOS worked well).

Packages:
```
"react-native": "0.64.2",
"react-native-webview": "11.4.4",
"react-native-youtube-iframe": "2.1.1",
```

Our usage code:
```
<YoutubePlayer
  height={200}
  videoId={videoId}
  webViewProps={{ androidHardwareAccelerationDisabled: true }}
/>
```

**Comment by LonelyCpp** [comment]
looks like a recent bug from rn-web-view.

some things to try : 
- update android system web view ([playstore link](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_IN&gl=US))
- set `android:hardwareAccelerated="true"` in android manifest
- try removing `androidHardwareAccelerationDisabled` prop

posting a few threads for reference : 
- https://github.com/react-native-webview/react-native-webview/issues/1632
- https://github.com/react-native-webview/react-native-webview/issues/1954

**Comment by maestor** [comment]
Yeah, looks like latest Android System WebView causes that because last upgrade is @ 16.8. and problems started after that.

When I try to enable hardware acceleration for Android, I got that WebView crashed with stacktrace:

```
Crashed: Thread :  SIGSEGV  0x0000000000000028
#00 pc 0x7cb8bb00f4 libhwui.so 
#01 pc 0x7cb8bb00a8 libhwui.so 
#02 pc 0x7cb8c51ca8 libhwui.so 
#03 pc 0x7cb8b8b54c libhwui.so 
#04 pc 0x7cb8b6f1f0 libhwui.so 
#05 pc 0x7cb9135ffc libhwui.so 
```

Don't remember anymore but that was the reason why it was disabled earlier.

Then found another issue related to SIGSEV error, and there was comment which works for me and now videos running perfectly again:  https://github.com/react-native-webview/react-native-webview/issues/429#issuecomment-732788998

So now I have:
1. android:hardwareAccelerated="true" in android manifest (probably enabled also by default so not sure if this needed)
2. In component, androidHardwareAccelerationDisabled prop dropped and added this style hack like:
```
<YoutubePlayer
  webViewStyle={{
    opacity: 0.99,
    minHeight: 1,
  }}
  height={200}
  videoId={videoId}
/>
```

Thanks @LonelyCpp for getting me into right direction, got also this hardware acceleration finally enabled for Android!

**Comment by fviazzi** [comment]
Thanks both @LonelyCpp and @maestor for posting solutions.

In my case `android:hardwareAccelerated="true"` did the trick, it was set to `false` by default.

Thanks again!

**Comment by LonelyCpp** [comment]
If you are using this with react navigation, the crash is probably due to animations. More documentation here : https://lonelycpp.github.io/react-native-youtube-iframe/navigation-crash

**Comment by Krishnakrish77** [comment]
I faced the same issue.
`<View className="flex-row p-2">
        <YoutubeIframe
                height={200}
                play={playing}
                videoId={trailer}
                onChangeState={onStateChange}
        />
</View>`

However I fixed it by removing the `flex-row` class!
