### ISSUE TITLE
Does this work with unejected Expo?

### ISSUE THREAD

**Issue by ralusek** [LonelyCpp/react-native-youtube-iframe#18]
I see expo support mentioned, but does this require it to be ejected?

**Comment by ralusek** [comment]
expo install react-native-webview

**Comment by sudipta-pran** [comment]
My expo app keeps crashing on the screen containing the video on android physical device. I have react-native-webview installed

**Comment by LonelyCpp** [comment]
hi @sudipta-pran I've tested it extensively on and android device. (expo and vanilla)

Can you give me details of 
* expo and webview versions
* the exception stack trace if possible

**Comment by sudipta-pran** [comment]
"expo": "^37.0.0"
"react-native-webview": "8.1.1"
Code that caused crashing:
`
const playerRef = useRef(null)
const [playing, setPlaying] = useState(true)
return (
<YoutubePlayer
                ref={playerRef}
                height={(9/16) * width}
                width={width}
                videoId={"AVAc1gYLZK0"}
                play={playing}
                forceAndroidAutoplay={Platform.OS === 'android'}
                onChangeState={event => console.log(event)}
                onReady={() => console.log("ready")}
                onError={e => console.log(e)}
                onPlaybackQualityChange={q => console.log(q)}
                volume={50}
                playbackRate={1}
                initialPlayerParams={{
                    cc_lang_pref: "us",
                    showClosedCaptions: true
                }}
                
                />
)
`

But when I use the minimal code, it works
`<YoutubePlayer
                height={(9/16) * width}
                width={width}
                videoId={"AVAc1gYLZK0"}
                />`

I am going through your [blog](https://lonelycpp.github.io/2020/03/15/react-native-youtube/), I've similar requirement from my app. Hope it'll work.

**Comment by LonelyCpp** [comment]
Seems to work for me 🤔 

It would be hard for me to debug it without seeing some kind of error log (the red log screen from react native). 

here's the test code - 
```
import React, { useState, useRef } from "react";
import { StyleSheet, View, Dimensions } from "react-native";
import YoutubePlayer from "react-native-youtube-iframe";

const { width } = Dimensions.get("window");

export default function App() {
  const playerRef = useRef(null);
  const [playing, setPlaying] = useState(true);

  return (
    <View style={styles.container}>
      <YoutubePlayer
        ref={playerRef}
        height={(9 / 16) * width}
        width={width}
        videoId={"AVAc1gYLZK0"}
        play={playing}
        forceAndroidAutoplay={Platform.OS === "android"}
        onChangeState={(event) => console.log(event)}
        onReady={() => console.log("ready")}
        onError={(e) => console.log(e)}
        onPlaybackQualityChange={(q) => console.log(q)}
        volume={50}
        playbackRate={1}
        initialPlayerParams={{
          cc_lang_pref: "us",
          showClosedCaptions: true,
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```

**Comment by sudipta-pran** [comment]
When I hit the back button, it crashes. How do I stop/remove from memory when I hit the back button(navigate back). I guess something to do with the ref?

**Comment by sudipta-pran** [comment]
Noticed something. I removed your module to see if video plays in just a webview. Still got crashes. Then I set the property
`androidHardwareAccelerationDisabled={true}`
in the webview component. Now it doesn't crash. But I really like to use your module. But it doesn't have this property. How do I set it?

**Comment by LonelyCpp** [comment]
Strange that hardware acceleration is causing a crash. You get access to all the webview properties with [webViewProps](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#webviewprops ) 

    webViewProps={{
          androidHardwareAccelerationDisabled: true,
        }}

**Comment by sudipta-pran** [comment]
Thanks. I was using `enableScreens` function of `react-native-screens`

Without this, the app doesn't crash. There is some conflict between react-native-screens and react-native-webview.

I hope this helps someone else too.
