### ISSUE TITLE
When playing the video it is not showing normal standard player else it is showing the youtube written player

### ISSUE THREAD

**Issue by affan00733** [LonelyCpp/react-native-youtube-iframe#188]
![WhatsApp Image 2021-09-12 at 1 28 36 PM](https://user-images.githubusercontent.com/42251896/132978904-37b31315-d3ca-4809-a520-5e76d9a3e30b.jpeg)

                           <YoutubePlayer
                            height={height * 0.3}
                            play={true}
                            videoId={this.state.video}
                      
                            playbackRate={this.state.playbackRate}
                        
                            initialPlayerParam={() => {
                                showClosedCaptions = true
                            }
                                
                            }
                        />

**Comment by LonelyCpp** [comment]
are you referring to the UI of the YouTube player?

**Comment by affan00733** [comment]
yes previously UI is different it does not have the youtube logo in player

**Comment by LonelyCpp** [comment]
The UI inside the player is fully controlled by youtube's player. This library does not customise / render any of it. 

so whatever you're seeing is the expected UI
