### ISSUE TITLE
autoplay with FullScreen 

### ISSUE THREAD

**Issue by vishalparmarmt** [LonelyCpp/react-native-youtube-iframe#19]
How to set in fullscreen video with autoplay?

**Comment by LonelyCpp** [comment]
Hey man sorry for the delay, I will look into this and let you know

**Comment by LonelyCpp** [comment]
setting `webViewProps={{allowsInlineMediaPlayback: false}}` and `playing={true}` will achieve fullScreen autoplay on iOS.

Android will default to inline play unfortunately, I'll keep you posted.

**Comment by butri71** [comment]
I'm using it with autoplay false as I have a gallery of videos.

Is there any way to hide the big red YouTube play button? Since I have to use a small size to begin with (w 200, h 130), that button looks pretty big.
Or at least can I control the size of that button?

Thanks
