### ISSUE TITLE
Play store reject android app

### ISSUE THREAD

**Issue by savan15** [LonelyCpp/react-native-youtube-iframe#193]
Hello 

We got rejection mail from the Google team 
![Screenshot 2021-09-23 160108](https://user-images.githubusercontent.com/75606567/134492915-d8893eb4-c716-4305-849d-153122650023.png)

Note : we got every time SSL error.

Please help me how to overcome this issue. 

And if you give suggestion like display popup so it is not properly  to showing every time to popup and user will decide can i 'continue' or 'cancel'

**Comment by LonelyCpp** [comment]
This is most likely an error from some other library using web views in an unsafe way.

The SSL handling has been properly handled in react-native-webview, so using the latest version will not result in rejections.

try this : https://github.com/react-native-webview/react-native-webview/issues/2118

for further help, try making an issue in the react-native-webview repo
