### ISSUE TITLE
Video reload on state changes 

### ISSUE THREAD

**Issue by samy-tcheik** [LonelyCpp/react-native-youtube-iframe#197]
When i click on a button to update a random state, the video player get reloaded again and the onReady event is fired again 

  const [videoLoading, setVideoLoading] = useState(true)

return (
     <View listKey='1'>
          <YoutubePlayer
            height={videoLoading ? 0 : 250}
            play={false}
            videoId={'ini9Euzsb6Y'}
            onReady={() => {setVideoLoading(false)}}
          />
        </View>
)

**Comment by LonelyCpp** [comment]
normal state changes ideally will not trigger a player reload.

can you make a small repo that reproduces this issue?

**Comment by bayramn** [comment]
I also experience this issue but not on snack. What could be reason for that?
