### ISSUE TITLE
Video can't auto play

### ISSUE THREAD

**Issue by PhamMinhKha** [LonelyCpp/react-native-youtube-iframe#2]
![Screenshot_1581136954](https://user-images.githubusercontent.com/12944689/74079319-21a90280-4a68-11ea-9a44-e5e81cf6dca0.png)
i try set play=true but not working
![Screen Shot 2020-02-08 at 11 45 33 AM](https://user-images.githubusercontent.com/12944689/74079338-8c5a3e00-4a68-11ea-848f-a20c261c5683.png)
![Screen Shot 2020-02-08 at 11 46 18 AM](https://user-images.githubusercontent.com/12944689/74079342-ab58d000-4a68-11ea-907b-d3e9bfb0c2c0.png)

**Comment by LonelyCpp** [comment]
what platform are you trying it on? ios or android?

**Comment by PhamMinhKha** [comment]
> what platform are you trying it on? ios or android?

I run on android. But you click button video play normal

**Comment by LonelyCpp** [comment]
Ok it looks like a bug on android. I will look into it and fix it ASAP. thanks :)

**Comment by LonelyCpp** [comment]
Hey, I've tried multiple things but there doesn't seem to be a very straightforward method to do this. This is due to autoplay rules enforced by chrome. 

> The HTML5 <video> element, in certain mobile browsers (such as Chrome and Safari), only allows playback to take place if it's initiated by a user interaction (such as tapping on the player).

more info here - https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

A quick work around for this would be to change your user agent with `webViewProps`. I just pushed this with a minor path version of `1.1.3`

```
<YoutubePlayer
        width={380}
        height={250}
        play={true}
        webViewProps={{
          userAgent:
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
        }} 
/>
```

Let me know if this works. Thanks :)

**Comment by PhamMinhKha** [comment]
@LonelyCpp thank you very much. but it not work for me 
![Screenshot_1582522610](https://user-images.githubusercontent.com/12944689/75130718-64bed300-5702-11ea-9817-aceb70451288.png)
i use "react-native-youtube-iframe": "^1.1.3"
![Screen Shot 2020-02-24 at 12 37 43 PM](https://user-images.githubusercontent.com/12944689/75130800-c1ba8900-5702-11ea-84e4-3e500efd273d.png)

**Comment by LonelyCpp** [comment]
Hey, try adding `mediaPlaybackRequiresUserAction: false` to webview props, like - 

```
webViewProps={{
          userAgent:
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
          mediaPlaybackRequiresUserAction: false,
        }}
```

**Comment by PhamMinhKha** [comment]
thank you reply. i try your new code but not working

**Comment by bobbyrinaldy** [comment]
hello, no update on this ?

**Comment by LonelyCpp** [comment]
@bobbyrinaldy 
Try the solution from this issue - #3 
Give it a try and let me know if its not working

**Comment by bobbyrinaldy** [comment]
> @bobbyrinaldy
> Try the solution from this issue - #3
> Give it a try and let me know if its not working

Seems working now, thanks. i have another question , should i make another issue or not ?

**Comment by LonelyCpp** [comment]
yes please
