### ISSUE TITLE
Why there is no volume buttons on my ios emulator?

### ISSUE THREAD

**Issue by Nicksapp** [LonelyCpp/react-native-youtube-iframe#202]
**Describe the bug**

there is no volume buttons on my ios emulator.
here is my code.

```js
<YoutubePlayer
  height={300}
  play={true}
  videoId={'xychGS2Mq2s'}
/>
```

**Screenshots**

![](https://z3.ax1x.com/2021/11/11/Iw0Wmq.png)

**Smartphone (please complete the following information):**
 - Device: iphone12
 - `react-native-youtube-iframe` newest 
 - `react-native-webview` newest

**Comment by LonelyCpp** [comment]
the controls UI is rendered by the youtube player, this library itself can't decide what to show
