### ISSUE TITLE
PlayListStartIndex not working

### ISSUE THREAD

**Issue by minhhoangzeno** [LonelyCpp/react-native-youtube-iframe#203]
<img width="703" alt="Screen Shot 2021-11-11 at 17 11 06" src="https://user-images.githubusercontent.com/83217409/141279926-17d809e2-17c8-4a57-a2df-03484aaa2b52.png">

**Comment by minhhoangzeno** [comment]
@LonelyCpp Can you help me with this bug?

**Comment by LonelyCpp** [comment]
hmm yes, seems like a bug in the library. I'll try to fix this when I get some time

**Comment by minhhoangzeno** [comment]
@LonelyCpp I'll wait you.

**Comment by minhhoangzeno** [comment]
@LonelyCpp sorry. Can you help me soon? I actually need.

**Comment by LonelyCpp** [comment]
Hey I probably will not be able to fix this very soon. 

you can try maintain the current video ID as a state variable or do some array manipulation to get around this issue

**Comment by minhhoangzeno** [comment]
@LonelyCpp Have you had time to help me?
