### ISSUE TITLE
2.2.0 play property not working.

### ISSUE THREAD

**Issue by aposto** [LonelyCpp/react-native-youtube-iframe#204]
<YoutubePlayer
        height={300}
        play={playing}
        videoId={"iee2TATGMyI"}
        onChangeState={onStateChange}
/>
play property true not auto playing. (playing is true)

**Comment by aposto** [comment]
if (!playerReady.current) {
      // no instance of player is ready
      return;
}

**Comment by LonelyCpp** [comment]
right, thanks! I've fixed this.
