### ISSUE TITLE
Question about the viewport meta tag

### ISSUE THREAD

**Issue by dpwilhelmsen** [LonelyCpp/react-native-youtube-iframe#21]
Hello! Thanks for writing this plugin! I was using this iframe technique in my application myself and I found this package that put it together nicely. However, after I started using this package, I started to get users complaining about not being able to "zoom in" on videos any more. I thought that was weird, but after looking into it, I guess my old implementation didn't have a `maximum-scale` set in the viewport meta tag. After removing it, zooming was allowed again.

Is there a way to make that max-scale configurable or removed? Or is this too much of a weird edge case and better handled in a private fork?

Thanks for your time, have a great day!

**Comment by LonelyCpp** [comment]
Hi @dpwilhelmsen 
The `maximum-scale` was deliberately put in removed to stop the zoom effect. Won't the webview overlap other components, or getting cropped by the containing view when zoomed in? 

I see you've made a fork and put in the change. If it works well for you, put in a prop (allowZoom?) to make it configurable and raise a PR :)

**Comment by dpwilhelmsen** [comment]
Hello!

Yeah, in most circumstances, you'd want to leave it restricted. You are correct that it would crop the contents of the video if they zoomed in. In our circumstance, people like to use it because we provide nature livestreams and if an animal is only in part of the frame, they like to bring it up closer.

I'll open an PR shortly with the modification. Thanks!

**Comment by LonelyCpp** [comment]
Hey, this change is pushed in v1.2.4! (with credits in the release notes 😄)

I'm curious to know if you're using this on a publicly available app. I'd love to see how it works

**Comment by dpwilhelmsen** [comment]
Thanks so much! Yes, the app is free in both the app store and the play store. Feel free to check it out!

https://apps.apple.com/us/app/explore-org/id534289239
https://play.google.com/store/apps/details?id=com.actolap.explore&hl=en_US
