### ISSUE TITLE
working on debug mode but not working after i build the apk

### ISSUE THREAD

**Issue by SaiChand440** [LonelyCpp/react-native-youtube-iframe#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` version 
 - `react-native-webview` version
 - `Expo` verison [if using expo]

**Additional context**

**Comment by LonelyCpp** [comment]
what is not working? please explain what you're seeing and what you expect.

**Comment by Udbhav9628** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS + version: [e.g. iOS 13.5 | Android 10]
> * `react-native-youtube-iframe` version
> * `react-native-webview` version
> * `Expo` verison [if using expo]
> 
> **Additional context** Add any other context about the problem here.

 Is problem resolved now sir???

**Comment by LonelyCpp** [comment]
closing as stale
