### ISSUE TITLE
Video Quality Remains Small even in fast internet

### ISSUE THREAD

**Issue by rohitsingh2410** [LonelyCpp/react-native-youtube-iframe#215]
Hi ,i have just implemented the video player but observed that Video quality of the videos is very poor. The OnPlayBackQuality change function always shows the quality as small.

Any suggestions?

**Comment by rohitsingh2410** [comment]
@LonelyCpp  Do you have any suggetions?

**Comment by kapilbhosale** [comment]
We are facing the same issue with high-speed internet.
