### ISSUE TITLE
 how make full screen mode, landscape mode

### ISSUE THREAD

**Issue by danil251** [LonelyCpp/react-native-youtube-iframe#219]
Please explain how to force open in landscape mode when opening full screen, android

**Comment by LonelyCpp** [comment]
You'll get a callback when a user goes into full screen mode on android.

You can then put the app in landscape mode using some API I guess? 

how to control app orientation is out of scope for this project. Let me know if you have any questions specific to the youtube player

**Comment by shubhamchepe** [comment]
Hey!,
Even if i am not using any of the orientation libraries, and when i turn on auto-rotate mode in android app and turn phone for landscape mode, the player works for fraction of second and returns back to previous screen

https://github.com/LonelyCpp/react-native-youtube-iframe/assets/34737632/37750ec8-0d64-4296-abde-2fb9d3deb409

![Screenshot (159)](https://github.com/LonelyCpp/react-native-youtube-iframe/assets/34737632/c774acda-96d8-430c-b94e-e35f1393ec5f)

**Comment by palashkulsh** [comment]
pieces of code for someone still looking


```
    import OrientationLocker from 'react-native-orientation-locker';

    const [isFullScreen, setIsFullScreen] = useState(false);

    const handleFullScreenChange = (isFullScreen) => {
        setIsFullScreen(isFullScreen);
        if (isFullScreen) {
            OrientationLocker.lockToLandscape();
        } else {
            OrientationLocker.lockToPortrait();
        }
    };

                <YoutubePlayer
                    ref={playerRef}
                    height={isFullScreen ? height*contentScale : 200}
                    width={isFullScreen ? width*contentScale : '100%'}
                    videoId={videoId}
                    play={true}
		    allowWebViewZoom={true}
                    onChangeState={(event) => console.log(event)}
                    onFullScreenChange={handleFullScreenChange}
		    contentScale= {contentScale}
                />
```
