### ISSUE TITLE
initialPlayerParams not working modestbranding

### ISSUE THREAD

**Issue by code4muktesh** [LonelyCpp/react-native-youtube-iframe#231]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` version 
 - `react-native-webview` version
 - `Expo` verison [if using expo]

**Additional context**

**Comment by LonelyCpp** [comment]
can you please actually fill in the above comment?

**Comment by code4muktesh** [comment]
npmPackages:
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

"react-native-webview": "11.15.0",
    "react-native-youtube-iframe": "^2.2.2",

**Comment by LonelyCpp** [comment]
What is not working? 

Can you clarify what your expectation is and what you're getting?

**Comment by code4muktesh** [comment]
Setting modestbranding flag 1 but youtube logo is still visible in video toolbar....this flag is not working. youtube logo is always visible whether set 0 or 1.

**Comment by IjzerenHein** [comment]
The `modestbranding` param seems to be working just fine for me (both iOS and Android). I did notice that when you change it, you'll need to re-mount the videoplayer.
Probably caused by the use of `useMemo` on this line:
https://github.com/LonelyCpp/react-native-youtube-iframe/blob/f3d115e2c5d235dc9b4aee61c6ee74b177c23336/src/YoutubeIframe.js#L227

**Comment by rvc2** [comment]
According to the YouTube development _revision history_, the modestbranding parameter has been deprecated and "will no effect." Details here: [YouTube modestbranding](https://www.rendervisions.net/youtube-modestbranding/).

**Comment by LonelyCpp** [comment]
looks like `modestbranding` has been deprecated by youtube. this parameter has no effect since August 15, 2023

https://developers.google.com/youtube/player_parameters#modestbranding
