### ISSUE TITLE
How to set video component size in 9:16? When I set width & height props, video component seems be controlled in 16:9 scale.

### ISSUE THREAD

**Issue by Nicksapp** [LonelyCpp/react-native-youtube-iframe#245]
How to set video component size in 9:16? 
When I set width & height props, video component seems be controlled in 16:9 scale. 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/15210887/161913110-9664a89f-1517-4e34-8374-347eae4c1738.png">

Can see that I set Player size to height:400, width:290, but video height can't set to 400.

**Comment by LonelyCpp** [comment]
if you want the player to expand into a custom height and ignore aspect-ratio, you can try this - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123
