### ISSUE TITLE
Android Full Screen Share Button and Redirecting to Youtube

### ISSUE THREAD

**Issue by abdulrehmanrfqt** [LonelyCpp/react-native-youtube-iframe#247]
How to Remove the share three dot button on full screen android and video name when video is on full screen mode.. it was working fine on 1.1.1 but in this later updates the Video name and share button showed up. Kindly help me with the work around. @LonelyCpp
![WhatsApp Image 2022-04-11 at 2 58 10 PM](https://user-images.githubusercontent.com/71380695/162715683-c40b83a4-aa0e-402a-8811-edd70104014b.jpeg)

**Comment by LonelyCpp** [comment]
unfortunately. YouTube does not allow removing the Overflow Menu or the share button.

you can try it on 1.1.1 too, if that works better.
