### ISSUE TITLE
Getting GitHub error in iframe

### ISSUE THREAD

**Issue by mzain512** [LonelyCpp/react-native-youtube-iframe#248]
**Describe the bug**
I try to load youtube trailers in the youtube iframe in my react native app.

<img width="313" alt="Screenshot 2022-04-23 at 5 28 59 PM" src="https://user-images.githubusercontent.com/32124157/164894555-76571048-5a45-4875-9e6c-e3885af2938b.png">

**Comment by LonelyCpp** [comment]
goes this happen all the time? works fine for me
