### ISSUE TITLE
Error: An error occurred.Please try again later.(Playback ID: ............)

### ISSUE THREAD

**Issue by sushantWemotive** [LonelyCpp/react-native-youtube-iframe#249]
After loading it shows error  'An error occurred.Please try again later.(Playback ID: ............)'

**Comment by MasoudJB** [comment]
Any solution for this issue? In my case I got HTML5_error

**Comment by kirkryan** [comment]
I get this, but only on videos that are vertical YouTube shorts - @LonelyCpp are there any known issues with YouTube shorts?

**Comment by harnie2275** [comment]
also getting this error

**Comment by eeshankeni** [comment]
Same problem here.

**Comment by itsfaraaz** [comment]
Anyone find a solution to this? Looks like it is isolated to some devices. In my case, it works fine on a physical device but fails to work on an iOS simulator.

**Comment by haideratGitHub** [comment]
Same problem here, trying to playback video on expo managed react native project in iOS simulator but give this error. Any solution ?

**Comment by anazcodesap** [comment]
Make sure you have passed videoURL, Thumbnail properly

**Comment by sriganesh-nagaraj** [comment]
Even im getting this error for some videos

**Comment by LonelyCpp** [comment]
https://github.com/LonelyCpp/react-native-youtube-iframe/issues/323
