### ISSUE TITLE
Controlling the native YouTube play button 

### ISSUE THREAD

**Issue by butri71** [LonelyCpp/react-native-youtube-iframe#25]
I'm using it with autoplay false as I have a gallery of videos.

Is there any way to hide the big red YouTube play button? Since I have to use a small size to begin with (w 200, h 130), that button looks pretty big.
Or at least can I control the size of that button?

Thanks

**Comment by LonelyCpp** [comment]
Hey @butri71 

If you have a gallery of videos, It's not a great idea to simply create player instances for each item. It's terribly inefficient and will slow your app down.

A better way to do this would be to use the [getYoutubeMeta](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#getyoutubemeta) call to fetch the thumbnail images of your videos and show them in an image view. These thumbnails DO NOT have the huge red play button :)

**Comment by butri71** [comment]
Thanks @LonelyCpp 

I'll give it a try tomorrow and see how it goes.

Appreciate the suggestion.

Cheers

**Comment by butri71** [comment]
Hi @LonelyCpp 

Ok Followed your suggestion and works very smoothly indeed.

Loading all thumbnails within a gallery and opening the player in a modal screen only when you click on the image.

I guess in this way you maximise performance as you don't need to load all videos, right?

I'm using this props webViewProps={{ allowsInlineMediaPlayback: false }} to expand the video in full screen but it only works horizontally. Is there any way to display the video in full screen mode?

Thanks

**Comment by LonelyCpp** [comment]
Great! 

#19 is kinda the same issue, I guess. The Youtube API does not give control over video orientation unfortunately. The user has to set the phone on landscape or press the fullscreen button as of now. :/

I'll let you know if there is a work around.
