### ISSUE TITLE
Traffic Source showing as github.io in YouTube Analytics

### ISSUE THREAD

**Issue by deependrasolanky** [LonelyCpp/react-native-youtube-iframe#255]
We have recently used this package for our Android App to play YouTube videos. While visiting analytics in the external traffic sources, I can see github.io as source name. My guess is that this source must be react-native-youtube-iframe package. Can anybody confirm? And is there any way to change the source name?

**Comment by LonelyCpp** [comment]
yes @deependrasolanky this is correct

more about it here : https://lonelycpp.github.io/react-native-youtube-iframe/self-host-remote-source

(you can host this on your own domains if required)
