### ISSUE TITLE
Unable to control fullscreen mode after preventing context menu touches (kebab + long press)

### ISSUE THREAD

**Issue by seanclaybaugh** [LonelyCpp/react-native-youtube-iframe#266]
**Describe the bug**
I am hosting some private youtube videos that I need to prevent others from sharing on our RN application. Unfortunately there is no way in the youtube API to control fullscreen without directly accessing the Youtube controls. It seems we must either allow link sharing, forgo fullscreen mode, or replicate fullscreen with a full screen webview + rotate which is not an acceptable interface. 

**Expected behavior**
Programmatically control full screen mode outside of the youtube controls or otherwise prevent link sharing of videos

**Comment by LonelyCpp** [comment]
unfortunately youtube does not give us an API to programatically control player fullscreen state.

you can check here : https://developers.google.com/youtube/iframe_api_reference
