### ISSUE TITLE
Monitized channels / ads enabled videos

### ISSUE THREAD

**Issue by fynally** [LonelyCpp/react-native-youtube-iframe#267]
How does this library handle videos with adverts?
All the YouTube channel videos that I have played in this library so far doesn't seem to display any kind of ads in the videos..
Is that normal?

**Comment by LonelyCpp** [comment]
here's info on where and how youtube decides to show ads on iframe embeds : https://support.google.com/youtube/answer/132596?hl=en

the videos you see from from this library has (https://github.com)[https://github.com/LonelyCpp/react-native-youtube-iframe/blob/2a3234c3f6de501fd059181d4315c4b50bf29657/src/constants.js#L42] as the base URL

you can change this to [your own domain](https://lonelycpp.github.io/react-native-youtube-iframe/self-host-remote-source), and work with google to enable ads for it.
