### ISSUE TITLE
Hide related videos and share option

### ISSUE THREAD

**Issue by sankarmahadevan** [LonelyCpp/react-native-youtube-iframe#269]
Hi, is there any way to hide related videos while pausing or end of the video? Also wanted to hide the share option. Please let me know if it's doable.

**Comment by LonelyCpp** [comment]
both are not possible to do using the iframe APIs provided by Youtube 

you can go through all the officially supported options here : https://developers.google.com/youtube/iframe_api_reference

this library serves as an interface to this, nothing extra can be added

**Comment by sankarmahadevan** [comment]
Thanks for your reply. Is there any other possible way to achieve my requirement? Basically, we have bunch of YouTube videos and wanted to play in RN app. All the videos are educational contents so, the user should not get distracted by other controls and related videos. Please provide your suggestions if you know any
