### ISSUE TITLE
Is the package compatible with react-native-webview@8.1.1?

### ISSUE THREAD

**Issue by jeanlucnguyen** [LonelyCpp/react-native-youtube-iframe#27]
It seems everything is working, but the peer dependency requires react-native-webview@^7.5.2, not react-native-webview@>=7.5.2
If so, is it possible to update the package.json file?

**Comment by butri71** [comment]
I'm using "react-native-webview": "8.1.1" in my project and works fine

**Comment by LonelyCpp** [comment]
@jeanlucnguyen 
It is compatible with all versions above 7.5.2. It should indeed by `react-native-webview@>=7.5.2`

I will update it in the next release. Thanks :)
