### ISSUE TITLE
Can I get captions of a youtube video and display it separately?

### ISSUE THREAD

**Issue by namlq93** [LonelyCpp/react-native-youtube-iframe#270]
I am making a bilingual app to learn English. I will insert a youtube video into the app, and show subtitles below. Is there any way I can get the captions directly from the youtube video player and display it separately?

![IMG_20220925_171456](https://user-images.githubusercontent.com/41458989/192454890-836e0fe7-318c-43ce-bda3-43e580758548.jpg)

**Comment by LonelyCpp** [comment]
no, this is not possible through this library. you can however look at the [youtube data api](https://developers.google.com/youtube/v3/docs/captions) to achieve similar results
