### ISSUE TITLE
emit elapsed time is not correctly 

### ISSUE THREAD

**Issue by HieuNguyen414** [LonelyCpp/react-native-youtube-iframe#271]
[https://lonelycpp.github.io/react-native-youtube-iframe/elapsed-time
](url)
I run app in emulator and tracking elapsed time in setinterval and video emit more than 1s (1,2s), what's wrong
` 
useEffect(() => {

    if (stateVideo === 'playing') {
      const interval = setInterval(() => {
        players.current?.getCurrentTime().then((current: number) => {
          setCurrentTime(current);
        });
      }, 100);
      return () => {
        clearInterval(interval);
      };
    }
  }, [stateVideo]);

`

screenshot
![image](https://user-images.githubusercontent.com/32530751/196132328-2475e89a-add3-4c63-9678-a74a0fdbd17c.png)

**Comment by LonelyCpp** [comment]
its not clear where you're printing this "run <x>", so not sure what you're actually printing here.

however you should know that set-interval does does not guarantee that your callback will be called exactly after the given time. They tend to drift a little depending on how occupied the main thread is. [here's a stackoverflow discussion about it](https://stackoverflow.com/questions/29971898/how-to-create-an-accurate-timer-in-javascript). You'd have to either increase sampling rate decrease accuracy in UI. 

This library is only responsible for giving you an elapsed time. Other timekeeping tasks are up to the consumer
