### ISSUE TITLE
iOS only issue: NSURLErrorDomain: Error Code -1202

### ISSUE THREAD

**Issue by fractalscape13** [LonelyCpp/react-native-youtube-iframe#277]
**Describe the bug**
Package installed, works on android and web but isn't working on iOS simulator.  The error is:
”Domain: NSURLErrorDomain 
Error Code: -1202
The certificate for this server is invalid.  You might be connecting to a server that is pretending to be “[lonelycpp.github.io](http://lonelycpp.github.io/)” which could put your confidential information at risk.”

**To Reproduce**
Install package with yarn in newly created bare rn app or expo-managed, attempt to run on iOS simulator

**Expected behavior**
Expected to see video

**Comment by param240** [comment]
I am also facing same issue. Any workaround please??

**Comment by param240** [comment]
```useLocalHTML={true}```

This worked for me.

**Comment by LonelyCpp** [comment]
possibly a duplicate of https://github.com/LonelyCpp/react-native-youtube-iframe/issues/323
