### ISSUE TITLE
Is it possible to hide the header for the youtube channel?

### ISSUE THREAD

**Issue by darias08** [LonelyCpp/react-native-youtube-iframe#283]
Hi,

I am wondering if it is possible if I can hide the youtube header? Like the youtube channel on the top left and the more button on the  top right side. I just want to have the youtube logo play button in the center with the thumbnail as the background. 

Here's a screenshot of what I mean:
![screenshot](https://user-images.githubusercontent.com/58616895/208277594-6282dc1a-ae4e-45b2-9b5e-a88385ff59e4.PNG)

**Comment by LonelyCpp** [comment]
this isn't possible with standard youtube APIs. 
(youtube's policy prevents you from publishing apps with such mods too)
