### ISSUE TITLE
not working in apple TV

### ISSUE THREAD

**Issue by rajscet** [LonelyCpp/react-native-youtube-iframe#293]

**Comment by sreuter** [comment]
@rajscet Can you elaborate on what exactly your issue is? Are you trying to use this with [React Native TVOS](https://github.com/react-native-tvos/react-native-tvos)?

**Comment by freeboub** [comment]
There is no webView on tvOS,  then this package cannot support tvOS

**Comment by LonelyCpp** [comment]
tvOS itself does not support webview : https://stackoverflow.com/questions/73633076/how-to-display-webpages-in-tvos-using-webkit
