### ISSUE TITLE
Video not work in android and ios build release

### ISSUE THREAD

**Issue by trugdn** [LonelyCpp/react-native-youtube-iframe#299]
Play video is not working on android, when running debug on emulator it works fine but when release build on real device it still doesn't work like android. it seems the YouTubeIframeAPIReady function is not working

**Smartphone (please complete the following information):**
 - Device: Android, IOS build release
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` : 2.2.2
 - `react-native-webview`: 13.2.2
 - `react`: 18.2.0
 - `react-native`: 0.71.0

update youtube app latest version

**Comment by sreuter** [comment]
@trugdn I noticed you closed the issue here. Where you able to resolve your issue?
