### ISSUE TITLE
YouTube player volume

### ISSUE THREAD

**Issue by pstmamao** [LonelyCpp/react-native-youtube-iframe#30]
Hi, would like to ask if the youtube player's volume output is a bug. 
It is in 100 but the audio output is low (both iOS and android)

**Comment by LonelyCpp** [comment]
Hi @pstmamao, the volume level is reflected in the player controls clearly on android. The iOS player may sometimes take system volume. Note that the player does not override the system volume, the levels are propotional to the system volume. I did a quick test on my android device to confim too. 

Let me know if you defenitely think its a bug. (with some device and OS version details)

**Comment by LonelyCpp** [comment]
Hey @pstmamao, 
Thanks for the kind words man ❤️ 

p.s: leave a star so the package can gain popularity 🙈
