### ISSUE TITLE
modestbranding flag not working with initialPlayerParams prop

### ISSUE THREAD

**Issue by gauravjoshi-vahan** [LonelyCpp/react-native-youtube-iframe#301]
**Describe the bug**
I'm adding the modestbranding flag inside the initialPlayerParams prop but it is not hiding the YoTube branding from the controls panel. 

**To Reproduce**
Playing any video in the player

**Expected behavior**
The YouTube name should be hidden from the controls panel on using this flag. 

**Screenshots**
<img width="367" alt="image" src="https://github.com/LonelyCpp/react-native-youtube-iframe/assets/106505836/5c3fdd2b-b2f8-44aa-8167-b1b391298a3a">

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 4 XL , API 33]
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` ^2.3.0 
 - `react-native-webview` 13.2.2
 - `Expo` verison [if using expo]

**Additional context**

**Comment by LonelyCpp** [comment]
looks like `modestbranding` has been deprecated by youtube. this parameter has no effect since August 15, 2023

https://developers.google.com/youtube/player_parameters#modestbranding

**Comment by LonelyCpp** [comment]
I'll add a deprecated notice in a future release
