### ISSUE TITLE
share button is not disabled when i go fullscreen

### ISSUE THREAD

**Issue by sandeep-autviz** [LonelyCpp/react-native-youtube-iframe#304]
sir i am using the recomended way to disable share which is to render a button and make it absolute . It did the job for me but when i go full screen i can still click at share button is there any way to fix this .

**Comment by LonelyCpp** [comment]
unfortunately, there's no way to disable player functions in fullscreen mode. youtube does not allow it.

**Comment by sandeep-autviz** [comment]
sir is there any way to play youtube videos in my app with the share functionality disabled
