### ISSUE TITLE
Can I play YouTube clip video ?

### ISSUE THREAD

**Issue by ranjitAcelucid** [LonelyCpp/react-native-youtube-iframe#307]
Hii @LonelyCpp and @all,

Can I play YouTube clip video using this library ? 

Thanks

**Comment by LonelyCpp** [comment]
Can you give me an example?

**Comment by ranjitAcelucid** [comment]
Okay
I want to play given youtube clip url using this library.

https://youtube.com/clip/Ugkxv7BLucV2Yhqej6SGjNBs9nxjlujf2vaF?si=kNcE5aUDKO8bVkBL

**Comment by LonelyCpp** [comment]
Clips are supported on their own. You'll have to add the original video id, start and end times

**Comment by ranjitAcelucid** [comment]
But How can I get original video id.
