### ISSUE TITLE
How to disable watch on youtube from the iframe

### ISSUE THREAD

**Issue by vijaykumar1710** [LonelyCpp/react-native-youtube-iframe#309]
**Describe the bug**

How to disable watch on youtube from the iframe

I want to disable watch on youtube, watch later and share options from the iframe. Please guide me in doing this.

**To Reproduce**
All videos by default has the watch on youtube, watch later and share options displayed on  iframe

**Expected behavior**
 I want to disable all of them,

**Smartphone (please complete the following information):**
 - Device:  any device
 - OS + version: any OS
 - `react-native-youtube-iframe` : latest
 - `react-native-webview` : latest

**Additional context**

**Comment by LonelyCpp** [comment]
this was previously possible thru the modest branding prop. But youtube has since deprecated it and there's no way to prevent a user from sharing the video or hiding the "watch no youtube" button

https://developers.google.com/youtube/player_parameters#august-15,-2023

**Comment by vijaykumar1710** [comment]
> this was previously possible thru the modest branding prop. But youtube has since deprecated it and there's no way to prevent a user from sharing the video or hiding the "watch no youtube" button
> 
> https://developers.google.com/youtube/player_parameters#august-15,-2023

Atleast can we handle onclick from those UI parts in the library?

**Comment by LonelyCpp** [comment]
no this isn't possible. the player is rendered inside an iframe by youtube. injecting custom js into it will be unreliable.

you can try experimenting with the [`injectjavascript`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectjavascriptstr) method
