### ISSUE TITLE
playerParams not working?

### ISSUE THREAD

**Issue by farzaa** [LonelyCpp/react-native-youtube-iframe#31]
Seems no matter what I do on iOS, player params aren't working!

```
      <YoutubePlayer
        height={"100%"}
        width={"100%"}
        ref={playerRef}
        videoId={"AVAc1gYLZK0"}
        play={playing}
        onChangeState={event => console.log(event)}
        onReady={() => console.log("ready")}
        onError={e => console.log(e)}
        onPlaybackQualityChange={q => console.log(q)}
        volume={50}
        playbackRate={1}
        playerParams={{
          preventFullScreen: true,
          start: 25,
        }}
      />
```

The above code doesn't actually prevent full screen i still am able to toggle full screen. Working in iOS w/ Expo.

**Comment by LonelyCpp** [comment]
Hi @farzaa 

This is indeed a bug on the default player provided by the webview in iOS. `preventFullScreen: true` seems to have no effect on it.

A workaround would be to change the user agent to chrome on macOS which will render the actual youtube player controls and it will hide the fullscreen button.
```
<YoutubePlayer
  {...otherProps}
  playerParams={{
    preventFullScreen: true,
    start: 25,
  }}
  webViewProps={{
    userAgent:
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
  }}
/>
```
user agent strings [source](https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome)

**Comment by farzaa** [comment]
Hm, so seems the same thing is happening where none of the player params actually work even w/ the user agent change. Testing on iOS iPhone 10.

**Comment by LonelyCpp** [comment]
I tried it on my emulator (iOS 13.4) and it seems to work fine - 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/18496510/83973328-48d2ec00-a903-11ea-9364-ba3a3ff221bc.gif)

What iOS version are you on? Also what version of react-native-webview are you using?

**Comment by farzaa** [comment]
Super weird.

iOS 13.2 iPhone 10 with:

```
    "react-native-webview": "8.1.1",
    "react-native-youtube-iframe": "^1.2.4"
```

Which doesn't work. This is the version of webview that comes w/ `expo install react-native-webview`.

**Comment by LonelyCpp** [comment]
I don't have access to a physical iPhone unfortunately :/ 
(all test devices are in office which is locked down due to COVID-19)

You can use the seek function on the `onReady` callback to replicate `start`
```
<YoutubePlayer
  ref={playerRef}
  play={true}
  onReady={() => {
    playerRef.current.seekTo(25);
  }}
/>
```

**Comment by LonelyCpp** [comment]
@farzaa Dude I finally figured it out. Almost pulled all my hair out thinginking what the could've gone wrong.

I made a typo in the example code, its not `playerParams`, it is `initialPlayerParams` [documentation](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#initialplayerparams) 

I'm really sorry! I hope you haven't moved on from this lib 💔

**Comment by hend-elsahli** [comment]
I applied `initialPlayerParams` instead of `playerParams` ... but still doesn't work ...

`          initialPlayerParams={{
            rel: false,
            showClosedCaptions: false,
            modestbranding: true,
          }}`

none of the params took effect unfortunately...

**Comment by LonelyCpp** [comment]
Hi @hend-elsahli can you tell me which platform you are trying it on and what was expected?

**Comment by hend-elsahli** [comment]
Hi,
I tried on the emulator, and I got black-screen (video title and progress bar load but with black-screen) 
black-screen issue disappeared when I tried on physical-device ... 

And yes `start: 25` works fine .. and I knew that `rel` and `showinfo` params are now deprecated ... but the one thing I do need to work is to disable captions ... can you help plz?


That was on Android - macOS

**Comment by LonelyCpp** [comment]
Yes, there is some problem with the emulator on older android versions. It will work on a android 10 emulator. (there is an issue tracking this - #29)

about the captions - can you share what video you are trying to play?

**Comment by bayramn** [comment]
Captions still not work in some videos weirdly and works others. In this it doesn't work: https://youtu.be/MGsalg2f9js
but click a CC button on controls it works. I want it to be automatically turned on.

**Comment by blackirishmec** [comment]
I can't get 'start' to work in initialPlayerParams in Expo RN:
```typescript
<YoutubePlayer
	height={playerHeight || 300}
	play={playing}
	videoId={videoId}
	onChangeState={onStateChange}
	initialPlayerParams={{
		start: 25,
		controls: false,
		color: 'red',
		iv_load_policy: 3,
		// rel: false,
	}}
	ref={playerRef}
/>
```
