### ISSUE TITLE
The Player is not shown when the parent View is aligned to center

### ISSUE THREAD

**Issue by choubari** [LonelyCpp/react-native-youtube-iframe#310]
When the parent view of the YouTubePlayer contains the style `alignItems: 'center'` , the player doesn't show anymore

Let's say we have a View (A) that contains a View (B) that contains the YouTubePlayer, even when the top level View A has  `alignItems: 'center'`, the player is not shown.

 - OS: Android and iOS
 - `"react-native-youtube-iframe": "2.3.0"` 
 - `"react-native-webview": "13.6.0"`

**Comment by LonelyCpp** [comment]
the player does not have default width. When the parent tells the payer to align itself to center, the width gets set to 0, and the player will not be rendered.

It'll show up if you give it a valid `width` prop value
