### ISSUE TITLE
SIGSEGV Error on android

### ISSUE THREAD

**Issue by SlavaC7** [LonelyCpp/react-native-youtube-iframe#311]
**Describe the bug**
hello everyone, I connected the library to "react-native": "^0.68.0" on android the application crashes when rendering an iframe, Sentry shows the SIGSEGV error
Segfault

**Screenshots**
<img width="638" alt="Знімок екрана 2023-10-09 о 15 44 25" src="https://github.com/LonelyCpp/react-native-youtube-iframe/assets/97901563/6093f1a8-1f39-4a51-b9aa-640370368e77">

**Smartphone (please complete the following information):**
 - Device: [TECHO SPARK, Readmi note 12 pro]
 - OS + version: [Android 13, Android 12]
 - `react-native-youtube-iframe` ^2.3.0 
 - `react-native-webview` "^13.3.1"
 - `react-native (CLI)` "^0.68.0" 

**Additional context**
Help pls

**Comment by LonelyCpp** [comment]
you'll have to post more details than this, there's no way to debug with the info you've provided.

you can search for crash related issues in the repo (for example : https://github.com/LonelyCpp/react-native-youtube-iframe/issues/216) and see if any of those work.

if you can reproduce the crash, you can add details and reopen this issue

**Comment by nathantew14** [comment]
I am also getting this exact crash. Only happens on android, and in production.
