### ISSUE TITLE
Add enablejsapi property

### ISSUE THREAD

**Issue by franmiorin** [LonelyCpp/react-native-youtube-iframe#319]
**Describe the bug**
I'm in need of the enablejsapi property to support [GA 4 tracking](https://www.analyticsmania.com/post/track-videos-with-google-analytics-4-and-google-tag-manager/). 

Video tracking in enhanced measurement works for embedded Youtube videos that have the JavaScript API enabled. That can be done by adding the enablejsapi=”true” attribute to the iframe, for example:
`<iframe src="https://www.youtube.com/embed/QfUSKYJz5QE" width="560" height="315" title="YouTube video player" enablejsapi="true" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; picture-in-picture" allowfullscreen></iframe>`

[enablejsapi](https://developers.google.com/youtube/player_parameters?hl=en#enablejsapi) is a parameter from the YouTube player

**Comment by LonelyCpp** [comment]
weird. the player is already being controlled by the js API. Initialising the player with `new YT.Player()` automatically enables this flag AFAIK.

I can add this flag in for good measure tho.

how do you plan on adding the GTM tag tho? 🤔
