### ISSUE TITLE
height is not working

### ISSUE THREAD

**Issue by Abubakarraza** [LonelyCpp/react-native-youtube-iframe#321]
when i give it height it does not work 
like in my case i give it 600 and it show video in 16/9 ratio but rest height taken by container

**Expected behavior**
If we give height it work

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS + version:Android and Ios both
 - `react-native-youtube-iframe` 2.3.0
 - `react-native-webview` 13.6.3
 - `Expo` verison 49.0.0

**Comment by LonelyCpp** [comment]
use this : https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123
