### ISSUE TITLE
Video Unavailable - Video is restricted Error

### ISSUE THREAD

**Issue by sandeep14** [LonelyCpp/react-native-youtube-iframe#323]
**Describe the bug**
While playing video in youtube iframe giving us error This video is restricted. Please check the The Google Workspace administrator annd/or the network administrator restriction

**To Reproduce**
Simply playing some video

**Expected behavior**
Video should be play

**Screenshots**

**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` version 

**Additional context**

**Comment by LonelyCpp** [comment]
is it happening on every public youtube video? or are you getting this on some custom video ID?

**Comment by sandeep14** [comment]
No, it is happening with specific video

**Comment by LonelyCpp** [comment]
the video is probably domain restricted. can you check the video settings and see if its fully visible to the public?

**Comment by sandeep14** [comment]
there are no any video restriction. For some device it is playing but for some device giving this issue

**Comment by LonelyCpp** [comment]
possibly a duplicate of https://github.com/LonelyCpp/react-native-youtube-iframe/issues/323
