### ISSUE TITLE
Height is ignored (doesn't work well for Shorts)

### ISSUE THREAD

**Issue by dominictobias** [LonelyCpp/react-native-youtube-iframe#336]
**Describe the bug**
Setting the height seems to have no effect - the video is still landscape. 

**To Reproduce**
```tsx
<YoutubePlayer
  webViewStyle={{ borderWidth: 1, borderColor: 'red' }}
  height={480}
/>
```

**Expected behavior**
Video should be portrait shaped

**Screenshots**
Instead the webview has a tall height, but the video is still landscape:

<img width="437" alt="Screenshot 2024-05-23 at 6 09 19 PM" src="https://github.com/LonelyCpp/react-native-youtube-iframe/assets/160451465/caba84fd-23d0-438b-96e0-9d504c87bbe8">

**Smartphone (please complete the following information):**
 - Device: iPhone15 Pro
 - OS + version: ios 17
 - `react-native-youtube-iframe` 2.3.0
 - `react-native-webview` 13.6.4
 - `Expo` verison 50

**Additional context**
It would be preferable for shorts to go straight to fullscreen mode as this fits portrait

**Comment by LonelyCpp** [comment]
if you want the player to expand into a custom height and ignore aspect-ratio, you can try this - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123
