### ISSUE TITLE
iframe not loading

### ISSUE THREAD

**Issue by StuartPyper** [LonelyCpp/react-native-youtube-iframe#338]
**Describe the bug**
The video on our app has stopped loading today. 
"onReady" never runs sothe video never loads, we are getting timeout messages for the url: https://lonelycpp.github.io/react-native-youtube-iframe/iframe.html

From Android device:
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -8, "description": "net::ERR_CONNECTION_TIMED_OUT", "loading": false, "target": 163, "title": "lonelycpp.github.io/react-native-youtube-iframe/iframe.html?data=%7B\"rel_s\":0,\"loop_s\":0,\"videoId_s\":\"tkkyOWlJ75U\",\"controls_s\":0,\"iv_load_policy\":3,\"contentScale_s\":1,\"cc_lang_pref_s\":\"\",\"allowWebViewZoom\":false,\"modestbranding_s\":1,\"preventFullScreen_s\":1,\"showClosedCaptions_s\":0%7D", "url": "https://lonelycpp.github.io/react-native-youtube-iframe/iframe.html?data=%7B%22rel_s%22:0,%22loop_s%22:0,%22videoId_s%22:%22tkkyOWlJ75U%22,%22controls_s%22:0,%22iv_load_policy%22:3,%22contentScale_s%22:1,%22cc_lang_pref_s%22:%22%22,%22allowWebViewZoom%22:false,%22modestbranding_s%22:1,%22preventFullScreen_s%22:1,%22showClosedCaptions_s%22:0%7D"}

From iOS simuator:
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1001, "description": "The request timed out.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 203, "title": "", "url": ""}

![Simulator Screenshot - iPhone 15 Pro - 2024-06-03 at 11 30 44](https://github.com/LonelyCpp/react-native-youtube-iframe/assets/35107139/7fb982e1-96fc-4e34-b53f-1104c7490538)

**To Reproduce**
Open app using react-native-youtube-iframe

**Expected behavior**
Video should play when loaded (as it did on Friday)

**Screenshots**

**Additional context**
I know this was definitely working on Friday, so it is a new issue.

**Comment by StuartPyper** [comment]
Note: the video we are trying to load is still available on YouTube and has not been made private: https://www.youtube.com/watch?v=tkkyOWlJ75U

**Comment by LonelyCpp** [comment]
closing this in favour of #337
