### ISSUE TITLE
onSeek function

### ISSUE THREAD

**Issue by batuhansahan** [LonelyCpp/react-native-youtube-iframe#34]
How to know if user seek spesific time is there a way to detect it ?

Does onChangeState provides this behaviour ?

**Comment by LonelyCpp** [comment]
The [YouTube player API](https://developers.google.com/youtube/iframe_api_reference) does not provide an onSeek event, so this isn't currently possible.

Although you can do a hacky implementation by running a javascript function in interval on `getCurrentTime` and check if the time difference measured is different from the one that is expected.
