### ISSUE TITLE
Rejected from App store

### ISSUE THREAD

**Issue by AdamElitzur** [LonelyCpp/react-native-youtube-iframe#342]
Hi,

I hope all is well! My app just got rejected from the App store using this library. I saw a previous issue from a few years ago, and included the YouTube API Terms of Service in the app review, but it is still getting rejected. I'm including the specifics below, but keep in mind I already included their terms of service, they just didn't accept it for some reason. Do you think it could be because I'm covering the iframe to prevent clicks, as mentioned in the docs?

Thanks so much for any help!

Guideline 5.2.3 - Legal

Your app contains content or features that may violate the rights of one or more third parties. Specifically, your app provides potentially unauthorized access to third-party audio or video streaming, catalogs, and discovery services. 

Your app and its contents should not infringe upon the rights of another party. In the event your app infringes another party’s rights, you are responsible for any liability to Apple because of a claim.

Next Steps

To resolve this issue, please attach documentary evidence in the App Review Information section in App Store Connect evidencing that you have all necessary rights or permissions to the third-party audio or video streaming, catalogs, and discovery services in your app. 

Once we have reviewed your documentation and confirmed its validity, we will proceed with the review of your app.

**Comment by AdamElitzur** [comment]
Nevermind I solved it by talking to a representative from the team and explaining this!

**Comment by ducpt-bili** [comment]
hi @AdamElitzur , how can you resolve this problem? Do you need to tell apple that the video content created from you? or you just make a call to explain to them? Thanks.

**Comment by isaacsolo** [comment]
hey @AdamElitzur do you recall what the resolution was? i've been waiting for a call with a rep and keep getting rejected

**Comment by AdamElitzur** [comment]
Hi, I ended up uploading a document explaining that it's within their terms of service, but it still got rejected. I needed to meet with a rep and explain on the phone for him to accept it. Without that it wouldn't work unfortunately.
