### ISSUE TITLE
Issues in styling the  youtubeplayer

### ISSUE THREAD

**Issue by SamarthKadam** [LonelyCpp/react-native-youtube-iframe#349]
<YoutubePlayer
        height={300}
        width={width-32}
        play={false}
        webViewStyle={{borderRadius:22}}
        videoId={"ylJKp7oLRyQ"}
        onChangeState={()=>{}}
      />
  I need to apply border radius to the youtube player I tried applying the style to webViewStyle and also to viewContainerStyle but I don't see any border radius.  Please check on this.

**Comment by fakhri-dot** [comment]
Hello, have you any solution about this?
