### ISSUE TITLE
Play Private and age restricted video with react-native-youtube-iframe

### ISSUE THREAD

**Issue by sandeep14** [LonelyCpp/react-native-youtube-iframe#351]
**Describe the bug**
We are not able to play age restricted and private video with react-native-youtube-iframe 2.3.0

**To Reproduce**
Simply play any agerestricted and private video with react-native-youtube-iframe 2.3.0

**Expected behavior**
Video Should be Play without any restriction

**Screenshots**
![IMG-20240130-WA0003](https://github.com/user-attachments/assets/2a58bb4d-17e8-43d3-81fc-6c3416ea241a)

**Smartphone (please complete the following information):**
happenig with all devices . react-native-youtube-iframe version is 2.3.0 and webview version is 13.12.2

**Comment by LonelyCpp** [comment]
The player operates on an anonymous context, so we won't be able to support user restricted videos

**Comment by sandeep14** [comment]
Ok ,With help of access token of autherized person , can we play private/age restricted video  , if yes how can we that access token with react-native-youtube-iframe player?
