### ISSUE TITLE
App crashing while switching screen to youtube player only in build apk

### ISSUE THREAD

**Issue by sjaiswalgit** [LonelyCpp/react-native-youtube-iframe#354]
I am Facing a issue where my YoutubePlayer works fine in debug apk but as soon i test it with release apk it crashing the app when i swicth to screen that has YoutubePlayer. I am using Expo based react native .
Expo version:51,
react-native-screens version:3.31.1
react-native-youtube-iframe version:2.3.0

**Comment by LonelyCpp** [comment]
Try the solutions here : https://lonelycpp.github.io/react-native-youtube-iframe/navigation-crash

**Comment by sjaiswalgit** [comment]
Tried but nothing works, my issue is its working fine in debug mode but when i release build it the app crashes as soon i change to that screen

**Comment by freeboub** [comment]
@sjaiswalgit nobody can understand you issue if you don't give minimal informations:
- the platform (android ios or both)
- the device (emulatator or reproduced on all devices)
- A log from logcat or xcode

**Comment by sjaiswalgit** [comment]
I am using android 13 .
Physical devical device got same using on multiple android device .
"dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-ml-kit/face-detection": "^1.3.2",
    "@react-native-picker/picker": "2.7.5",
    "@react-navigation/native": "^6.0.2",
    "@shopify/react-native-skia": "^1.3.10",
    "axios": "^1.7.5",
    "date-fns": "^4.1.0",
    "expo": "~51.0.26",
    "expo-asset": "~10.0.10",
    "expo-build-properties": "~0.12.5",
    "expo-constants": "~16.0.2",
    "expo-file-system": "~17.0.1",
    "expo-font": "~12.0.9",
    "expo-image-manipulator": "~12.0.5",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.21",
    "expo-screen-orientation": "~7.0.5",
    "expo-secure-store": "~13.0.2",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-video": "^1.2.5",
    "expo-web-browser": "~13.0.3",
    "jpeg-js": "^0.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-fast-tflite": "^1.3.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-toast-message": "^2.2.0",
    "react-native-vision-camera": "^4.5.1",
    "react-native-vision-camera-face-detector": "^1.7.1",
    "react-native-web": "~0.19.10",
    "react-native-worklets-core": "^1.3.3",
    "react-native-youtube-iframe": "^2.3.0",
    "vision-camera-resize-plugin": "^3.1.0"
  },
logcat: 09-28 17:54:33.490  6497  6551 E ReactNativeJS: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCWebView' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["HeadlessJsTaskSupport","PlatformConstants","SourceCode","DeviceInfo","UIManager","DeviceEventManager","RNCSafeAreaContext","IntentAndroid","NativeAnimatedModule","SoundManager","I18nManager","Timing","ReanimatedModule","ImageLoader","Appearance","StatusBarManager","StatusBarManager","BlobModule","Networking","Worklets","AppState"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","RedBox","BugReporting","LinkingManager","NativeReactNativeFeatureFlagsCxx","RNSModule","FrameRateLogger","KeyboardObserver","ModalManager","RNCWebView"]}, js engine: hermes
09-28 17:54:33.500  6497  6551 E ReactNativeJS: TypeError: Cannot read property 'ErrorBoundary' of undefined
09-28 17:54:33.500  6497  6551 E ReactNativeJS:
09-28 17:54:33.500  6497  6551 E ReactNativeJS: This error is located at:
09-28 17:54:33.500  6497  6551 E ReactNativeJS:     in SceneView
09-28 17:54:33.500  6497  6551 E ReactNativeJS:     in RCTView
09-28 17:54:33.500  6497  6551 E ReactNativeJS:     in Unknown

**Comment by sjaiswalgit** [comment]
Got my issue fixed need to install react-native-webview library additionaly
