### ISSUE TITLE
Unable to change height of the video frame

### ISSUE THREAD

**Issue by sanaf1333** [LonelyCpp/react-native-youtube-iframe#355]
I am displaying shorts and videos on my app. For shorts i want the height to be 500 and for videos i want it to be 350 but no matter what height i set it stays consistent somewhere around 300. Setting height prop doesn't change anything. What is the purpose of that prop? It just adds white space below the component. Moreover, if i don't set play to true the video doesn't play on clicking on the youtube play sign. Instead when I click on video name it takes me to the youtube page.

**Expected behavior**
Setting height prop should change the height of video.

Device: Iphone 15 pro max

**Comment by LonelyCpp** [comment]
https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123

**Comment by sanaf1333** [comment]
@LonelyCpp this doesn't answer my question about autoplay. If I don't set the video on autoplay I am unable to play it at all by clicking on play button, I have to click on the header of video which then takes me to youtube in browser
