### ISSUE TITLE
Styling & Rounded Corners

### ISSUE THREAD

**Issue by CodeWithShreyans** [LonelyCpp/react-native-youtube-iframe#356]
I tried styling it with a `<View>`, even using CSS child selectors but that didn't seem to work. What's the best way to round the player's corners?

**Comment by LonelyCpp** [comment]
have you tried overflow hidden?

<img width="961" alt="Screenshot 2024-10-11 at 10 08 35 PM" src="https://github.com/user-attachments/assets/a8178793-9211-4c82-b9af-b6b161961961">
