### ISSUE TITLE
Fullscreen in modal

### ISSUE THREAD

**Issue by xdarkleonx** [LonelyCpp/react-native-youtube-iframe#36]
If YoutubePlayer in modal window, when you click fullscreen, you cant see him because he places under modal. Any ideas how to fix this?

**Comment by LonelyCpp** [comment]
Hi,

There is a known bug in `react-native-webview` right now, where **fullscreen mode** from a modal is buggy on **android**(iOS works fine). We will have to wait for them to fix the issue :(

[link to issue](https://github.com/react-native-community/react-native-webview/issues/1293)

**Comment by LonelyCpp** [comment]
@xdarkleonx I can confirm that setting `coverScreen={false}` with react-native-modal fixes this problem. Can you try it and let me know?

**Comment by xdarkleonx** [comment]
@LonelyCpp Yes react-native-modal coverScreen={false} works. Thank you.
