### ISSUE TITLE
[Android] Fullscreen mode not working

### ISSUE THREAD

**Issue by federicomiralles** [LonelyCpp/react-native-youtube-iframe#37]
**Describe the bug**
Even though I have set **allowsFullscreenVideo: true** within **webViewProps** the video is still being playing in regular mode (I think it's called inline) on Android.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS + version: Android 9 (Pie)
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 10.3.1
 - `react-native` 0.62.2

**Additional context**
```
<YoutubePlayer
          play={playing}
          height={75}
          width={150}
          videoId={YOUTUBE_VIDEO_ID}
          webViewProps={{
            allowsInlineMediaPlayback: false,
            allowsFullscreenVideo: true,
          }}
          onChangeState={state => {
            if (state === 'paused' || state === 'ended') {
              setPlaying(false);
            }
          }}
          initialPlayerParams={{
            modestbranding: true,
          }}
        />
```

**Comment by LonelyCpp** [comment]
Hi, `allowsInlineMediaPlayback` is an iOS only flag. [documentation](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#allowsinlinemediaplayback)

Android (chrome) by default plays videos inline at the moment, and there is no way to force fullscreen as of now. I am looking at ways to solve this in android. I'll keep you posted!
