### ISSUE TITLE
modestbranding not working

### ISSUE THREAD

**Issue by federicomiralles** [LonelyCpp/react-native-youtube-iframe#38]
**Describe the bug**
Setting up **modestbranding: true** doesn't seen to be working neither on iOS nor on Android. Youtube play button is still being displayed...

**Smartphone (please complete the following information):**
 - Device: any
 - OS + version: iOS 13.5.1 and Android 9
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 10.3.1
 - `react-native` 0.62.2

**Additional context**
```
<YoutubePlayer
          play={playing}
          height={75}
          width={150}
          videoId={YOUTUBE_VIDEO_ID}
          webViewProps={{
            allowsInlineMediaPlayback: false,
            allowsFullscreenVideo: true,
          }}
          onChangeState={state => {
            if (state === 'paused' || state === 'ended') {
              setPlaying(false);
            }
          }}
          initialPlayerParams={{
            modestbranding: true,
          }}
        />
```

**Comment by LonelyCpp** [comment]
are you referring to the youtube play button before the video starts?

**Comment by LonelyCpp** [comment]
It will be better if you can attach a screenshot

**Comment by federicomiralles** [comment]
Hi @LonelyCpp! First of all thanks for your quick answer. This is icon I mean:

![Untitled](https://user-images.githubusercontent.com/53195495/85797901-e192a580-b712-11ea-896e-9ef3354da163.png)

Cheers,

Federico

**Comment by LonelyCpp** [comment]
Yep, this is the player thumbnail. Modest-branding will not remove that unfortunately. You can try the workaround mentioned [here](https://github.com/LonelyCpp/react-native-youtube-iframe/issues/38#issuecomment-649563299)
