### ISSUE TITLE
Disable text selection on iOS

### ISSUE THREAD

**Issue by federicomiralles** [LonelyCpp/react-native-youtube-iframe#40]
**Describe the bug**
Blue text selection handles are shown on top of the video

**To Reproduce**
1) Tap on the **3 vertical dots** icon on the upper right corner of the video iframe
2) Then click on the **Share** option 
3) Finally tap on the **3 horizontal dots** once and close the overlay from the **X** icon
4) Blue text selection handles will appear randomly on top of the video...

**Expected behaviour**
Text selection should be optional

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/53195495/86420119-ec69af00-bcab-11ea-8188-60f376ab84b1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS + version: iOS 13.5.1
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 10.3.1
 - `react-native` 0.62.2

**Additional context**
I tried to disable the text selection following the info provided [here](https://github.com/react-native-community/react-native-webview/issues/607#issuecomment-567402064) but unfortunately it didn't work:
```
const INJECTED_JAVASCRIPT = "document.body.style.userSelect = 'none'";
...
<YoutubePlayer
          play={playing}
          height={VIDEO_HEIGHT}
          width={VIDEO_WIDTH}
          videoId="AVAc1gYLZK0"
          initialPlayerParams={{
            modestbranding: true,
          }}
          webViewStyle={styles.webView}
          webViewProps={{
            injectedJavaScript: INJECTED_JAVASCRIPT,
          }}
          onReady={() => setVideoReady(true)}
        />
```

**Comment by LonelyCpp** [comment]
Good catch @federicomiralles, I will look into the issue tonight 😄 

p.s: Since you've raised a few concerns, I'm curious if you are using this an app that's out there. I'd love to check it out!

**Comment by psdevss** [comment]
Hi, did you manage to solve this?

**Comment by LonelyCpp** [comment]
Hey no, couldn't really figure out whats causing this. Didn't really look deeper

**Comment by LonelyCpp** [comment]
tried a few things here, none of them worked unfortunately. Closing this issue since I don't think it's anything major

**Comment by aaulthudl** [comment]
Hi, I was looking into this issue myself and saw that you mentioned https://github.com/react-native-webview/react-native-webview/issues/607 here.

For my React Native app I had to use `-webkit-user-select: none` instead of `user-select: none`. I also added it to the style of the page rather than overwriting it to be safe. Perhaps this could work for you also if it is still something of value?

In the example above it would instead be:
```
const INJECTED_JAVASCRIPT = "document.body.style += '-webkit-user-select: none;'";
...
<YoutubePlayer
          play={playing}
          height={VIDEO_HEIGHT}
          width={VIDEO_WIDTH}
          videoId="AVAc1gYLZK0"
          initialPlayerParams={{
            modestbranding: true,
          }}
          webViewStyle={styles.webView}
          webViewProps={{
            injectedJavaScript: INJECTED_JAVASCRIPT,
          }}
          onReady={() => setVideoReady(true)}
        />
```
