### ISSUE TITLE
responsive size for web view

### ISSUE THREAD

**Issue by franjorub** [LonelyCpp/react-native-youtube-iframe#42]
Hi, is there a way to set something like 

width: 100%;
height: auto;

instead of fixed values ? thanks.

**Comment by franjorub** [comment]
I made a  workaround using Dimensions

**Comment by manuhook** [comment]
Hi @franjorub, can you share your solution ?
Thanks !

**Comment by O-r-D** [comment]
@franjorub Hey there  👋

Can you please share your Dimensions workaround?

**Comment by juspriet** [comment]
height={Dimensions.get('window').width * 9 / 16}

**Comment by juspriet** [comment]
To respect 16:9 video ratio ! 

> @franjorub Hey there  👋
> 
> Can you please share your Dimensions workaround?

height={Dimensions.get('window').width * 9 / 16}
To respect 16:9 video ratio !
