### ISSUE TITLE
Player resolution

### ISSUE THREAD

**Issue by brunodlabs** [LonelyCpp/react-native-youtube-iframe#47]
Hey! I noticed player resolution is always 16:9. 
This can be changed? 
How?

Thanks!

**Comment by LonelyCpp** [comment]
can you try this - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/13#issuecomment-611753123

**Comment by brunodlabs** [comment]
@LonelyCpp Awesome, thanks you some much!
**Another question:** 
It's possible to automatically go into **full screen** without user having to touch full screen button?

**Comment by brunodlabs** [comment]
@LonelyCpp Your comment works fine (It is ignoring resolution now) but if you go full screen and back to normal size 
you will see this weird layout on android (It's like a embeb video now with title, share button and watch latter button)
On iOS this doesn't happen, but you can see title, watch later and share buttons for some miliseconds before you go into full screen.

Before:

<img width="318" alt="Screen Shot 2020-07-22 at 1 38 47 PM" src="https://user-images.githubusercontent.com/50216253/88203768-b2435b80-cc20-11ea-86fd-83e4068f319e.png">

After:

<img width="318" alt="Screen Shot 2020-07-22 at 1 34 36 PM" src="https://user-images.githubusercontent.com/50216253/88203110-2f220580-cc20-11ea-893f-f957bc925184.png">

Any idea why this is happening? This is my code
<img width="495" alt="Screen Shot 2020-07-22 at 1 36 25 PM" src="https://user-images.githubusercontent.com/50216253/88203490-5c6eb380-cc20-11ea-889e-d2b0e2249f9a.png">

**Comment by LonelyCpp** [comment]
> is it possible to automatically go into full screen without user having to touch full screen button?

Unfortunately, this is not possible at the moment. There's nothing in their APIs that control this ☹️ 

## fullscreen issue 

yeah, unsetting the `position` property seems to mess with fullscreen mode. I tried it too, doesn't work. Here's something you can try - 

```
injectedJavaScript: `
            var element = document.getElementsByClassName('container')[0];
            element.style.paddingBottom = <ASPECT_RATIO>;
            true;
          `,
```

you need to calculate the aspect ratio you would like to for the player to resize to. Right now the default is `56.25%` (16:9). The formula would be `(height of player / width of player) * 100`

Try it out and let me know 😄
