### ISSUE TITLE
[help wanted] Want to play video in loop

### ISSUE THREAD

**Issue by Prashantrao331** [LonelyCpp/react-native-youtube-iframe#48]
Hey First of all thank you for this wonderful package. 

Is there any option by which we can play video in loop because i dont want to show suggested video screen at the end of the video.  Or something to not show suggested video at the end.

**Comment by LonelyCpp** [comment]
If you want to loop a single video, you could seek the video to the start just as it ends. `onChangeState` called with "ended" when the video ends, paired with the `seekTo` function should do the trick.

here's a snippet - 
```
<YoutubePlayer
  ref={playerRef}
  play={playing}
  videoId={"AVAc1gYLZK0"}
  onChangeState={(state) => {
    if (state === "ended") {
      playerRef.current.seekTo(0);
    }
  }}
/>
```

**Comment by Prashantrao331** [comment]
Thank you so much, it works perfect. I have few more things to ask :
1. Can we hide the top info bar ?
2. Is it possible to show a loader till video is getting ready?

**Comment by LonelyCpp** [comment]
1. Top bar cannot be hidden unfortunately :/ Youtube does not allow this
2. Yes! just show an overlay with an ActivityIndicator till the video loads up. You can use `onChangeState` again to wait for the "playing" event to fire

example - 
```javascript
export default function App() {
  const playerRef = useRef(null);
  const [playing, setPlaying] = useState(true);

  // loading state true by default
  const [videoLoading, setVideoLoading] = useState(true);

  return (
    <View style={styles.container}>
      <View style={{ height: 250 }}>
        <YoutubePlayer
          ref={playerRef}
          height={250}
          width={width}
          play={playing}
          videoId={"AVAc1gYLZK0"}
          onChangeState={(state) => {
            switch (state) {
              case "playing":
                // video is done loading
                setVideoLoading(false);
                break;
              case "ended":
                playerRef.current.seekTo(0);
                break;
            }
          }}
        />
        {videoLoading && ( // show overlay only when vide is loading
          <View
            style={{
              alignItems: "center",
              backgroundColor: "red",
              justifyContent: "center",
              ...StyleSheet.absoluteFill, // covers the video
            }}
          >
            <ActivityIndicator />
            <Text>loading video</Text>
          </View>
        )}
      </View>
    </View>
  );
}
```

**Comment by Prashantrao331** [comment]
Thank you so much, you are truly a life saver 👍 

And thank you for this amazing package.
