### ISSUE TITLE
Some videos show "Video unavailable" 

### ISSUE THREAD

**Issue by TimMun** [LonelyCpp/react-native-youtube-iframe#5]
Some videos are displaying with a "Video unavailable" error. You can test with this video: https://youtu.be/JGp_5gOww0E

I suspect it's a similar issue to https://github.com/davidohayon669/react-native-youtube/issues/314 , (same video behaved similarly with that library). I'm not getting an onError callback with this error.

```
return (
        <YouTubePlayer
          videoId={'JGp_5gOww0E'} 
          play={true}
          onError={e => this.setState({ youtubeError: e })}
          height={300}
          width={400}
        />
      )
```

**Comment by LonelyCpp** [comment]
Hello @TimMun 

The video that you are trying to play (`JGp_5gOww0E`) is set to **embed_not_allowed**. 
The owner of the requested video **does not** allow it to be played in embedded players.

You can use the `onError` callback to handle errors and show meaningful error messages to your users - [documentation](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#onError)

**Comment by TimMun** [comment]
Yes, you're right, for some reason my onError wasn't firing earlier but now it is.

**Comment by SurajMDurgad** [comment]
It throws `embed_not_allowed` even for videos which work if we use the embedded iframe from youtube.
Video ID - HCjNJDNzw8Y
Iframe which works - 
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/HCjNJDNzw8Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by LonelyCpp** [comment]
@SurajMDurgad https://www.youtube.com/embed/HCjNJDNzw8Y does not work on my chrome browser either. 

<img width="705" alt="Screenshot 2020-07-03 at 3 38 25 PM" src="https://user-images.githubusercontent.com/18496510/86458730-57b29000-bd43-11ea-8406-948c8ed8fa84.png">

Can you double check if this exact video plays on an embedded iframe for you?

**Comment by SurajMDurgad** [comment]
When you open the URL in an iframe it works.
https://codepen.io/SurajMDurgad/pen/KKVZBoQ

**Comment by davidwico** [comment]
I have same issue
Did you found a solution @SurajMDurgad ??

**Comment by SurajMDurgad** [comment]
Hey @davidwico,
I wasn't able to resolve the issue using this package, I ended up using react native webview and hosted a URL which returns an iframe. I created a medium post on how exactly I've built it. Feel free to drop a comment.
https://medium.com/@surajmdurgad/embedding-youtube-videos-in-a-react-native-app-8c556a18fd76

**Comment by LonelyCpp** [comment]
Great article @SurajMDurgad, but theres no clear reason as to why this works - Hosting a domain just to play youtube videos 🤯

**Comment by SurajMDurgad** [comment]
@LonelyCpp I prefer to have something which works with all the cases, rather than having something work with only few specific cases which is sort of half baked. 
No one knows what's the exact reason - https://stackoverflow.com/a/51971125
Sometimes it's better to make the things work, rather than worrying about the documentation. If there was any documentation available this issue wouldn't have occured in the first place.
I didn't have to host a entirely new domain for this to work, I already had domain which I used for my APIs, it was just a matter of adding a subdomain. If that's the case, people can use it. I'm just sharing what worked for me.

**Comment by LonelyCpp** [comment]
Woah there mate. Didn't mean to sound offensive, apologises if I did! Happy to see it worked :)

**Comment by SurajMDurgad** [comment]
I did find it offensive but still it was a valid question, that's the reason I took time to get all the facts straight. Any how mate thanks for package. Your effort is greatly appreciated. Thanks again! 😁

**Comment by tuanphamanh91** [comment]
In library 'react-native-youtube' I see they set: 
origin="http://www.youtube.com" to resolve this problem.

Can we do that @LonelyCpp?

https://github.com/davidohayon669/react-native-youtube/issues/314

**Comment by hoangdvAT** [comment]
> In library 'react-native-youtube' I see they set: origin="http://www.youtube.com" to resolve this problem.
> 
> Can we do that @LonelyCpp?
> 
> [davidohayon669/react-native-youtube#314](https://github.com/davidohayon669/react-native-youtube/issues/314)

you saved my day!
