### ISSUE TITLE
[help wanter] Iframe issue on Back from full screen

### ISSUE THREAD

**Issue by Prashantrao331** [LonelyCpp/react-native-youtube-iframe#50]
Hey,

Whenever i came back from fullscreen mode and with paused or playing, it show the complete youtube frame. attached screenshot of the same.

Note: Facing this issue in Latest android version (android 10), not in old ones.

![WhatsApp Image 2020-07-28 at 6 10 56 PM](https://user-images.githubusercontent.com/5758302/88666589-e970ab80-d0fd-11ea-9deb-628302fc9b67.jpeg)

**Comment by LonelyCpp** [comment]
sorry for the delayed response. Is this similar to #32 ?

If so - the work around is to give height and width values that are slightly above or below a 16 : 9 aspect ratio. (eg - 320 x 180 leads to this problem but 325 x 180 (slightly larger height) will fix this problem.

**Comment by Prashantrao331** [comment]
Thanks it works fine in android 10.

Few other things:
1. In android 6 when i entered in fullscreen mode the app is crashing or hanging.
2. Can we add a back button in the fullscreen mode?

**Comment by LonelyCpp** [comment]
1. Can you post a stack trace of the crash? (hook it up to logcat in android studio) I'm can't seem to reproduce a crash on the android emulator running Marshmallow.
2. An overlay over the player is not possible when in fullscreen.
3. A fullscreen callback is something I'm working on, but not currently available.
