### ISSUE TITLE
Dynamically Append PlayList doesn't update Youtube Playlist

### ISSUE THREAD

**Issue by pyxploiter** [LonelyCpp/react-native-youtube-iframe#52]
**Describe the bug**
Dynamically Append PlayList doesn't update Youtube Playlist.

**To Reproduce**
Add state variable for list of Video IDs, and append the list dynamically. Use that state variable in the Player PlayList.

```
...
this.state = {
      playList:["tAPVdPLCvYU"],
}
...
<YoutubePlayer
              ref={c => this.playerRef = c}
              height="100%"
              width="100%"
              playList={this.state.playList}
              play={false}
              onChangeState={this.onVideoChangeState}
              onReady={this.onVideoReady}
              onError={e => console.log("OnError",e)}
              onPlaybackQualityChange={q => console.log("OnQualityChange:",q)}
              volume={100}
              playbackRate={1}
              initialPlayerParams={{
                cc_lang_pref: "us",
                showClosedCaptions: true,
                preventFullScreen: true,
              }}
            />
```

**Expected behavior**
Youtube playlist should be updated.

**Comment by LonelyCpp** [comment]
The playlist is sent into the player during initialization, any changes after that won't show until the component is mounted again. 

If you have dynamic playlists - I suggest you to maintain a list of videos and playing index to pass them in as individual videoIds. This way you'll have more control over which video is playing and will not cause reloads on the player.

Let me know if you need help with that :)

**Comment by pyxploiter** [comment]
> The playlist is sent into the player during initialization, any changes after that won't show until the component is mounted again.
> 
> If you have dynamic playlists - I suggest you to maintain a list of videos and playing index to pass them in as individual videoIds. This way you'll have more control over which video is playing and will not cause reloads on the player.
> 
> Let me know if you need help with that :)

Aah I see. Thanks for the idea.
