### ISSUE TITLE
share not working in Android, and How can i disable more videos?

### ISSUE THREAD

**Issue by Akash-T2S** [LonelyCpp/react-native-youtube-iframe#53]
**Describe the bug**
While trying to share, nothing happens or responding.

**To Reproduce**
Press share icon.

**Expected behavior**
Share should work.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi note 4
 - OS + version: Android 7
 - `react-native-youtube-iframe` 1.2.4 
 - `react-native-webview` 7.5.1 
 - `Expo` verison [if using expo]

**Additional context**
Is there and option to hide share if possible, and also is it possible to hide more videos (Next suggested) once current video ended as nothing happens if i press any suggested video.

**Comment by LonelyCpp** [comment]
Hi @Akash-T2S, you are correct, the context menus in the videos (especially suggested and share) are not handled by the library explicitly. This is due to `onShouldStartLoadWithRequest` by default always returns false as seen below
https://github.com/LonelyCpp/react-native-youtube-iframe/blob/b3bd90abf6e3aa6e497a85dd3b99f2a57040fa4e/src/YoutubeIframe.js#L189

If you want to handle them properly you ought to override it using [webViewProps](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#webviewprops)

```
webViewProps={{
  onShouldStartLoadWithRequest: (request) => {
    // your custom handling here
    }
  }}
```

>is there and option to hide share, and more videos

unfortunately YouTube does not allow this in their APIs

**Comment by Akash-T2S** [comment]
Hi @LonelyCpp Thanks for your quick response, i have few more doubts regarding the player for Android.
`<YoutubePlayer
                            height={250}
                            width={SCREEN_WIDTH - 10}
                            videoId={item.video_id}
                            play={false}
                            volume={50}
                            playbackRate={1}
                            playerParams={{
                                cc_lang_pref: 'us',
                                showClosedCaptions: true
                            }}
                        />`

These are the props which i use, everything works as charm but when i try to view full screen the video is not displayed intermittently although the sound plays in background (1: 10). If there is solution please let me know. Below are the changes i have tried from my end 
`<YoutubePlayer
                            height={250}
                            width={SCREEN_WIDTH - 10}
                            videoId={item.video_id}
                            play={false}
                            volume={50}
                            playbackRate={1}
                            playerParams={{
                                cc_lang_pref: 'us',
                                showClosedCaptions: true
                            }}
                            forceAndroidAutoplay={Platform.OS === 'android'}
                        />`
This changed the UI of the player which works fine and when i try to view in fullscreen the fullscreen icon is not visible. It will be better if i could get any of the solution to proceed. Thanks.

**Comment by Akash-T2S** [comment]
Hi @LonelyCpp , In Android when i try to play multiple videos simultaneously the app gets crashed with no error (Intermittent - (2:4)). `<YoutubePlayer
                            height={SCREEN_HEIGHT / 2.59}
                            width={SCREEN_WIDTH - 10}
                            videoId={item.video_id}
                            play={false}
                            volume={50}
                            playbackRate={1}
                            playerParams={{
                                cc_lang_pref: 'us',
                                showClosedCaptions: true
                            }}
                            forceAndroidAutoplay={Platform.OS === 'android'}
/>`

It happens in both debug and release build. Help needed. Thanks

**Comment by LonelyCpp** [comment]
> app gets crashed with no error

Sounds like a native crash. You will be able to get a stack trace from android studio. [more details here](https://developer.android.com/studio/debug/am-logcat#running). Post the stack trace here so I can help you better

**Comment by LonelyCpp** [comment]
> when i try to view full screen the video is not displayed intermittently although the sound plays in background

1. If your video is on a modal, try this - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/36#issuecomment-647535272
2. Are you running your app on an emulator with android API 28 or 29? (to check if it's similar to #29)

if not, can you post a small screen recording of the issue?

**Comment by staticGuru** [comment]
https://www.npmjs.com/package/react_native_youtube_streamer
