### ISSUE TITLE
Missing onProgress

### ISSUE THREAD

**Issue by aftabaig** [LonelyCpp/react-native-youtube-iframe#57]
I want to setup my own seekbar and need an `onProgress` callback. Is this possible?

**Comment by LonelyCpp** [comment]
Hey you'll have to use  `getCurrentTime` with a setTimeout when the player becomes ready.

Here's a sample implementation from an earlier thread - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/9#issuecomment-608309028

Just make sure you start the interval after player is ready, and stop it when the player is unmounted. You can give any ms delay to tune the accuracy.

**Comment by aftabaig** [comment]
Thanks for your reply @LonelyCpp 
That's what I did and it worked!

**Comment by jazzdragon** [comment]
@LonelyCpp this is a good workaround, however an `onProgress` callback implementation would be very useful.
