### ISSUE TITLE
Not working in stack navigator

### ISSUE THREAD

**Issue by Talhafayyaz11** [LonelyCpp/react-native-youtube-iframe#61]
**Controls are disabled in stack navigator**
Users cannot pause or play the video when the screen is wrapped under stack navigator. 

Would really appreciate your help. Thanks

**Comment by LonelyCpp** [comment]
Hi @Talhafayyaz11 

That's rather odd. The stack navigator usually will not affect how this component works. 

Can you share a snippet of how you've used the youtube component?

**Comment by Talhafayyaz11** [comment]
Thanks for help it was my internal issue.
