### ISSUE TITLE
changing design

### ISSUE THREAD

**Issue by Esmail99** [LonelyCpp/react-native-youtube-iframe#63]
I want to hide youtube logo and the 3 dots from the video ,
simply i want users not able to get the video link one way or another.

is it supported ?

**Comment by LonelyCpp** [comment]
It is not possible to change to UI of the player. 

You can however achieve this using react native. Place an absolutely positioned view on the player (either fully covering the player or just tall enough to cover the title) to prevent the webview from receiving user touches.
Let me know if you want a sample snippet of code.

p.s: It will be against their ToS to do this

**Comment by LonelyCpp** [comment]
Hi @gaurav-techefficio 
Here's a small example - 

```jsx
import React from "react";
import { TouchableOpacity } from "react-native";
import { View } from "react-native";
import YoutubePlayer from "react-native-youtube-iframe";

export default function App() {
  return (
    <View>
      <YoutubePlayer height={300} videoId={"XSqi5s3rfqk"} />
      <TouchableOpacity
        // TouchableOpacity to "steal" taps
        // absolutely positioned to the top
        // height must be adjusted to 
        // just cover the top 3 dots
        style={{
          top: 0,
          height: 50,
          width: "100%",
          position: "absolute",
        }}
      />
    </View>
  );
}
```

**Comment by staticGuru** [comment]
New package for render the YouTube videos.
https://www.npmjs.com/package/react_native_youtube_streamer

**Comment by LonelyCpp** [comment]
@staticGuru please stop spamming random issues with links to your package

**Comment by staticGuru** [comment]
@LonelyCpp sorry for your inconvenience.

Previously we have used your package. But, we can't hide the UI.
So, we build that package.

Kindly use and share your feedbacks.
