### ISSUE TITLE
Quality Video Youtube is missing

### ISSUE THREAD

**Issue by bobbyrinaldy** [LonelyCpp/react-native-youtube-iframe#7]
i just copy and paste the example on fresh react-native project,

it is working properly but i realize that video quality is missing, i cannot change the quality.

what is the problem i missed ?

RN : 0.61
react-native-youtube-iframe : 1.2.0

**Comment by LonelyCpp** [comment]
Unfortunately programatically setting video quality is not allowed by youtube. 

[API Doc](https://developers.google.com/youtube/iframe_api_reference#Revision_History) | [Youtube Doc](https://support.google.com/youtube/answer/91449)
> the API no longer supports functions for setting or retrieving playback quality. To give you the best viewing experience, YouTube adjusts the quality of your video stream based on your viewing conditions.

The user can still manually change quality, for which there is a callback if you want - [doc](https://github.com/LonelyCpp/react-native-youtube-iframe/tree/master/doc#onplaybackqualitychange)
