### ISSUE TITLE
Background play

### ISSUE THREAD

**Issue by Jonoh89** [LonelyCpp/react-native-youtube-iframe#72]
Hi, I have recently added this library to an app on the Play Store and it got taken down for "Device and Network Abuse policy". I queried the issue and received this as a reply:

> Step 1: Fix the policy violations with your app
During review, we found that your app violates the Device and Network Abuse policy by enabling background play of YouTube videos.
For example, to illustrate background play is when the audio of a YouTube video continues to play even after the user has navigated away from the page containing that video. (ex: your app continues to play videos when the device is in lock screen mode.) 

Has anybody else come across this? Testing on my pixel device the player seems to stop when I lock the device or close/navigate away from the app. I tried to ask for more details on device/version but I received "Unfortunately, I'm unable to comment on your inquiry about the device models.".

I not calling any methods, simply allowing user to play using the youtube controls from inside the iframe

**Comment by LonelyCpp** [comment]
Hi @Jonoh89 
Sad to hear that :( 
app reviews are sometimes frustrating as they don't properly tell you what went wrong

Here are a couple of things you can do 
* use [AppState](https://reactnative.dev/docs/appstate.html) to make sure the youtube video pauses when the app is "inactive" 
* make sure you don't have opaque overlays over the video
* make sure the video view port is not too small
* use navigation life cycle (blur / focus in case of react navigation) to properly pause a video if in playing state

**Comment by Jonoh89** [comment]
thanks for the help! 

I wont leave this open as it could take a while until I find out but I will try using AppState 👍. then the others, though I don't think it could be them.

Will maybe add a line to a the readme if I can get them to acknowledge that this was the fix

**Comment by mladenkn** [comment]
Hello there,

Is it still possible to have a video playing in the background?

I have just tried the library, and it seems like a new default is that video doesn't play in background? However, is it possible to achieve this? This app that I'm developing will not be published on the app store, so I want this functionality.

@LonelyCpp 

Thank you

**Comment by TSB1999** [comment]
@mladenkn Did you figure out how to play it in the background?

**Comment by mladenkn** [comment]
> @mladenkn Did you figure out how to play it in the background?

Nope, seems to me like this isn't supported anymore. I think that Google made it impossible to implement. Or at least supper hard.

**Comment by 2004durgesh** [comment]
Did u find a hack around to play video in background?

**Comment by TSB1999** [comment]
The implementation isn't legal apparently. So they have made it impossible to facilitate background play. Sorry

Try iframe and unpause the player if you detect it going into the background. At worst there will be a 1 second delay.

**Comment by buscanopaul** [comment]
up
