### ISSUE TITLE
Add Play/Pause in Player Function.

### ISSUE THREAD

**Issue by pqv2210** [LonelyCpp/react-native-youtube-iframe#73]
Hello @LonelyCpp , i use your library in a React Native Class component and i can't pause/play video when is unfocused my screen. Can't you update it?
Thank you. ❤️

**Comment by LonelyCpp** [comment]
Hi @pqv2210 

You can simply set the `play` prop to true or false. 

For example in case of class components: 
```jsx
class App extends React.Component {
  state = {
    playing: true
  }

  togglePlaying = () => {
    this.setState(prev => {playing: !prev.playing});
  }

  render(){
    return (
      <View>
        <YoutubePlayer
          height={300}
          play={this.state.playing}
          videoId={"iee2TATGMyI"}
        />
        <Button title={this.state.playing ? "pause" : "play"} onPress={togglePlaying} />
      </View>
    );
   }
}
```

let me know if you need more help :)

**Comment by pqv2210** [comment]
Thank for your help, i will try. xD

**Comment by pqv2210** [comment]
One more time, thank for you help. I resolved my problem. ❤️
