### ISSUE TITLE
Video not looping

### ISSUE THREAD

**Issue by devster19** [LonelyCpp/react-native-youtube-iframe#74]
**Describe the bug**
video stop playing, although loop property was set to true in initialPlayerParams

**Expected behavior**
youtube video should replay

**Smartphone (please complete the following information):**
 - `react-native-webview` version  "10.10.0"
 - `Expo` verison  "expo": "~39.0.2",

**Comment by LonelyCpp** [comment]
If you are trying to loop a single video, the iframe player can misbehave as mentioned [here](https://developers.google.com/youtube/player_parameters#loop).

You can try the suggested alternative where you must send an array with a single video id to `playlist`, with loop set to `true`
 
p.s: would be helpful if you can post a small snippet where this is reproducible

**Comment by devster19** [comment]
Thank you for your time
I have followed your suggestion and use playlist instead of videoid  but video dont loop 
and trying both on Expo and React Native
please have a look at my code below do I make a wrong config?
`
import React from "react";
import {  View, StatusBar, SafeAreaView, Dimensions } from "react-native";
import YoutubePlayer from "react-native-youtube-iframe";
const App = () => {
  const {width, height} = Dimensions.get("window")
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView style={{flex: 1}}>
        <View style={{flex: 1, justifyContent:'center'}}>
          <YoutubePlayer
            width={width}
            height={300}
            initialPlayerParams={{controls: false, loop: true}}
            play={true}
            playList={["pQ1E_Ln7328", "VCDrdVjP5ww"]}
          />
        </View>
      </SafeAreaView>
    </>
  );
};


export default App;
`

**Comment by LonelyCpp** [comment]
Hi @devster19 
you are correct, it seems that `loop` does not seem work in this manner. However, creating a playlist on youtube and passing that in loops the videos as expected.

Here for example I created a playlist with the videos you used in the list, and used it like this - 

```jsx
playList={"PLBQuNCO44hlIyw_ZRGxeFqoxsDwMS6rm7"}
initialPlayerParams={{ loop: true }}
```
note: the playlist must be **public**

**Comment by LonelyCpp** [comment]
let me know if this method does not work for you
