### ISSUE TITLE
Cross-site Scripting (XSS) in react-native-webview

### ISSUE THREAD

**Issue by goutham8343** [LonelyCpp/react-native-youtube-iframe#75]
Would this cause problem since react-native-webview is installed as a dependency and Cross-site Scripting is a security vulnerability in it?

**Comment by LonelyCpp** [comment]
I don't think this is a concern. The webview is sandboxed and there's not a lot a XSS script can do on a webview sitting inside a react native app context. The base URL is also null, so CORS also will kick in.

You have full access to the internal webview through `webViewProps`, so you can put in any measures that are available through its API.

Let me know if you have specific concerns that I must look into.
