### ISSUE TITLE
Full screen display is disabled

### ISSUE THREAD

**Issue by freewebwithme** [LonelyCpp/react-native-youtube-iframe#8]
React Native 0.62
react-native-youtube-iframe 1.2.0
Trying in real android device

I tried this
`<YoutubeIframe height={250} videoId={'someVideoId'} initialPlayerParams={{ preventFullScreen: false}} />`

It display full screen button, but it is disabled to click.
How can I use display full screen function?

**Comment by LonelyCpp** [comment]
hi @freewebwithme 
Can you try the solution in #6? Let me know if it is't working
