### ISSUE TITLE
Seek function

### ISSUE THREAD

**Issue by psdevss** [LonelyCpp/react-native-youtube-iframe#80]
Hi, would like to ask if I can seek to a time without the status changing to 'pause'

**Comment by LonelyCpp** [comment]
Hi @psdevss 

* calling [seekTo](https://lonelycpp.github.io/react-native-youtube-iframe/component-ref-methods#seekto) will not trigger the "pause" state
* scrubbing the timeline on the player itself puts the video on a "paused" state till the user releases the slider.

There is no way to control how these events are fired. This library only delegates the events to react native.
