### ISSUE TITLE
Some videos not playing

### ISSUE THREAD

**Issue by jerber** [LonelyCpp/react-native-youtube-iframe#81]
Some videos, especially ones involving music (and likely Copywrite issues) are not playing.

An example is the video with id: o1KWG3yRd2k, which plays fine on youtube: https://www.youtube.com/watch?v=o1KWG3yRd2k&ab_channel=AudienVEVO.

**Comment by LonelyCpp** [comment]
Hey, are you sure embeds are allowed for this video? 

Video content creators can explicitly mark their videos "embed not allowed". You will get this as an error from `onError` prop.

more discussions about this here - https://github.com/LonelyCpp/react-native-youtube-iframe/issues/5
