### ISSUE TITLE
Disable Long press on a video

### ISSUE THREAD

**Issue by Tilenozz** [LonelyCpp/react-native-youtube-iframe#82]
When i ,accidentally , long press on a video , this strange menu appeared.

![iframe](https://user-images.githubusercontent.com/54805850/97892756-b78c6800-1d30-11eb-9261-6434181c9c10.png)

I looked at Webview , and tried to edit the Css , but not worked.
How to disable Long press ?

**Comment by LonelyCpp** [comment]
Hi, this is the options menu from the youtube web player. (long press on phones, right click menu on desktop)

Unfortunately, there is no way to remove this from the webview itself. 

You could try some solutions on react native with gestures ([docs](https://reactnative.dev/docs/gesture-responder-system)). You can try attaching a handler or a long press, but let short taps through.

**Comment by MaheshGawhane11** [comment]
Save issue. anyone found solution for this?

**Comment by davidcort** [comment]
Same issue.

**Comment by hadnet** [comment]
Anybody could solve this issue? Any solution on this, @LonelyCpp ?

**Comment by yogesh-jgu** [comment]
Anybody could solve this issue? Any solution to this?

**Comment by LonelyCpp** [comment]
#224
