### ISSUE TITLE
I am unable to get the control options play/stop options when i used this youtubeplayer,even i am unable to play the video ,

### ISSUE THREAD

**Issue by ramkgunturu** [LonelyCpp/react-native-youtube-iframe#86]
I am unable to get the control of an youtube video start/stop/pause/fullscreen.

Please some one guide me on this issue,

Below is my code 
<TouchableOpacity
            style={{marginTop: 10, width: 100, height: 200}}
            onPress={() => onSelect(item, index)}>
   
            <YoutubePlayer
              height={300}
              width={300}
              apiKey={YOUR_API_KEY}
              play={index === selectedId ? true : false}
              videoId={videopath}
              onReady={(e) => isReady}
              onFullScreenChange={index === selectedId ? true : false}
              onChangeState={(e) => setStatus(e.state)}
              playerParams={{
                controls: true,
              }}
            />
          </TouchableOpacity>

i  installed react-native-webview version 10.0.0

**Comment by LonelyCpp** [comment]
Can you upload a screenshot? 

It could be possible that the viewport is small, try increasing the `width` prop

**Comment by ramkgunturu** [comment]
I think height is not a problem it seems because options are not available and touch is not working when i click on the video

**Comment by LonelyCpp** [comment]
you've wrapped the video with a `<TouchableOpacity />`, so the player will not receive any touch events (all touch events to go to `onPress`)

What are you trying to achieve with that Touchable? The style seems weird with explicit `width: 100, height: 200`.

**Comment by ramkgunturu** [comment]
Thanks I have removed TouchableOpacity and its working fine...

**Comment by ramkgunturu** [comment]
Thanks I have removed TouchableOpacity and its working fine...
