### ISSUE TITLE
An error occurred. Please try again later.

### ISSUE THREAD

**Issue by micheilsgrey** [LonelyCpp/react-native-youtube-iframe#88]
**Describe the bug**
For some reason in iOS some videos not working and showing text: ' An error occurred. Please try again later.' And this happening only on the real device, on the simulator all working correctly. Some videos open with no problem and some don't.

**Expected behavior**
Expecting working the same as on simulator, without errors.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/8958040/100477692-26739b80-30fa-11eb-9f73-7fb754910c42.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X / iPhone 11(Simulator)
 - OS + version: iOS 13
 - `react-native-youtube-iframe` version: ^1.4.0
 - `react-native-webview` version: ^10.7.0

**Additional context**

My code: 

```typescript 

export default class YoutubePlayer extends Component<PlayerProps, PlayerState> {
  _shareVideo = (video: Video) => {
  ...
  };

  render() {
    const { video } = this.props.route.params;
    return (
      <SafeAreaView style={styles.mainContainer}>
        <View style={styles.topBar}>
          <TouchableOpacity
            onPress={this.props.navigation.goBack}
            style={styles.topBarClose}>
            <Image style={{ marginLeft: 8 }} source={images.closeModal} />
          </TouchableOpacity>

          <TouchableOpacity
            onPress={() => this._shareVideo(video)}
            style={styles.topBarShare}>
            <Image
              style={{ position: 'absolute', right: 8 }}
              source={images.share}
            />
          </TouchableOpacity>
        </View>
        {Platform.OS === 'android' ? (
          <YouTube
            apiKey={GLOBAL.YOUTUBE_API_KEY}
            videoId={video.id} // The YouTube video ID
            controls={1}
            // play
            // fullscreen
            play={Platform.OS === 'ios' ? false : true} // control playback of video with true/false
            fullscreen={Platform.OS === 'ios' ? false : true} // control whether the video should play in fullscreen or inline
            style={{ alignSelf: 'stretch', height: width * 0.56 }}
          />
        ) : (
          <YoutubeIframe
            height={width * 0.56}
            play={true}
            videoId={video.id}
            //onChangeState={onStateChange}
          />
        )}
        <View style={styles.bottomBar}>
          <View style={styles.titleView}>
            <Text numberOfLines={2} style={styles.title}>
              {video.title}
            </Text>
          </View>
          <View style={styles.viewsTimeContainer}>
            <View style={styles.views}>
              <Image style={styles.viewsImage} source={images.viewsYoutube} />
              <Text style={styles.textFormat}>{formatViews(video.views)}</Text>
            </View>
            <View style={styles.duration}>
              <Image style={{}} source={images.durationYoutube} />
              <Text style={styles.textFormat}>
                {formatSeconds(video.length)}
              </Text>
            </View>
          </View>
        </View>
        <View style={styles.bottom}>
          <Image
            style={styles.channelLogo}
            source={{ uri: video.channelThumbnails.high.url }}
          />
          <Text style={styles.channnelName}>{video.channelName}</Text>
        </View>
      </SafeAreaView>
    );
  }
}

```

**Comment by LonelyCpp** [comment]
Hey can you add an `onError` callback and see if it sends our an event? - [documentation](https://lonelycpp.github.io/react-native-youtube-iframe/component-props#onerror)

**Comment by micheilsgrey** [comment]
> Hey can you add an `onError` callback and see if it sends our an event? - [documentation](https://lonelycpp.github.io/react-native-youtube-iframe/component-props#onerror)

```typescript 
 onError={(e) => alert(e.error)}
```
![Image from iOS](https://user-images.githubusercontent.com/8958040/100520759-9f352f00-31b0-11eb-828d-bab0099f01c9.png)

**Comment by micheilsgrey** [comment]
As you can see in the code I am trying another component/lib too:  `react-native-youtube`. It has the same error in iOS, in android working correctly.

**Comment by LonelyCpp** [comment]
Yes the other youtube player also uses the iframe embed method used in this library for ios. 

Here's the description by youtube's api -

> The requested content cannot be played in an HTML5 player or another error related to the HTML5 player has occurred.

This error is closely tied to the system webview provided by iOS. You can probably find some pattern the the iOS versions of phones with this issue, since webview updates are distributed as an os update. 

Since you can reliably get a callback when this error happens, you can try to reload the player (remove and remount the player).

**Comment by micheilsgrey** [comment]
I will try this, thank you.

**Comment by LonelyCpp** [comment]
Hey, did you fix this issue? (a small summary will be helpful for future reference)

**Comment by micheilsgrey** [comment]
> Hey, did you fix this issue? (a small summary will be helpful for future reference)

Sadly, not. I update webview, actually, I update the whole project with about 15 libs. Nothing changed. The same error even after reloading of Iframe. I used the `XCDYoutubeKit` standalone player with `react-native-youtube` because the Iframe is broken.

**Comment by micheilsgrey** [comment]
Update with my issue. Looks like the my problem has something to do with iOS version in the simulator i was with outdated iOS 13. An after we tested the app with a real device with iOS 14 we had this issue with youtube. Even after i swap iframe to `XCDYoutubeKit` we have the same issue on iOS 13 all working fine on 14 and real device almost every video not working...
