### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by yasintz** [LonelyCpp/react-native-youtube-iframe#90]
**Describe the bug**
I am running getCurrentTime 2 times per second and so gives the error.
```sh
[MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 getCurrentTime listeners added. Use emitter.setMaxListeners() to increase limit]
```
**To Reproduce**
I'm running a setInterval in useEffect. Sometimes I get the above error. I think it's caused by the EventEmitter.

**Smartphone (please complete the following information):**
 - Device: General Mobile GM 9 pro
 - OS + version: Android 9
 - `react-native-youtube-iframe` 1.4.0 
 - `react-native-webview` 11.0.0

**Comment by LonelyCpp** [comment]
Hey this is due to queries to `getCurrentTime()` BEFORE the `onReady()` callback. 

Can you try starting the `setInterval()` after `onReady()` is called?

**Comment by LonelyCpp** [comment]
something like this - 

```jsx
const [playerReady, setPlayerReady] = useState(false);

useEffect(() = >{
  let timer;
  if(playerReady) {
    timer = setInterval(() => { ... }, 500);
  }

  return () => clearInterval(timer);
}, [playerReady]);

return (
  <YoutubeIframe
    ...
    onReady={() => setPlayerReady(true);
  />
);
```

**Comment by yasintz** [comment]
@LonelyCpp I do it that way too. but it still gives this warning.

**Comment by yasintz** [comment]
As this problem persists, I reopened this issue.
I am using flatlist and call getCurrrentTime with setInterval. This error happens after a while. How can I dissolve?
