### ISSUE TITLE
Getting SSL error due to fonts file.

### ISSUE THREAD

**Issue by ATOM49** [LonelyCpp/react-native-youtube-iframe#95]
Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": 3, "description": "SSL error: The certificate authority is not trusted", "loading": false, "target": 18733, "title": "about:blank", "url": "https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9AMP6lQ.ttf"}

**Comment by LonelyCpp** [comment]
Hey, does this happen all the time? 

The library does not load any font on its own - so its probably some font that youtube is trying to load for it's UI.
