### ISSUE TITLE
PlayList does not seem to work, when using PlayList throws invalid parameter error

### ISSUE THREAD

**Issue by hmhm2292** [LonelyCpp/react-native-youtube-iframe#97]
**Describe the bug**
When trying to use playList with array of videoIds it seems to not work.
**To Reproduce**
Create a array with videoIds and play

**Expected behavior**
Expected to see a playlist

**Screenshots**

**Smartphone (please complete the following information):**
 - OS + version: [e.g. iOS 13.5 | Android 10]
 - `react-native-youtube-iframe` version 
 - `react-native-webview` version
 - `Expo` verison [if using expo]

**Additional context**

**Comment by LonelyCpp** [comment]
definitely a bug, I'm working on fixing it

**Comment by LonelyCpp** [comment]
Hello, this has been fixed in a patch release! (https://github.com/LonelyCpp/react-native-youtube-iframe/commit/0564f6595e8daecbdfb287ad025334b2dc2c4886)

please update version to `v1.4.1`
