### ISSUE TITLE
Can't touch full screen on iPad

### ISSUE THREAD

**Issue by matsu0228** [LonelyCpp/react-native-youtube-iframe#99]
**Describe the bug**

Can't touch full screen on iPad.
The full screen button is disabled and show message of "Your browser dosen't support full screen"

**To Reproduce**

our app is developed by Expo39 bareworkflow(React Native 0.63)
use following props.
```
        <YoutubePlayer
          height={200}
          play={true}
          videoId={dhV8x98Utb}
          forceAndroidAutoplay={true}
          initialPlayerParams={{}}
        />
```

**Expected behavior**

The full screen button is active and can be pressed to display full screen.

**Screenshots**

<img width="518" alt="Screen Shot 2021-01-15 at 16 57 20" src="https://user-images.githubusercontent.com/5501329/104699263-d27a5000-5755-11eb-846b-d74f32a1aff4.png">

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS + version:  iOS 14.3 iPad Pro (12.9-inch) (4th generation)
 - `react-native-youtube-iframe` version  **1.3.0**
 - `react-native-webview` version **10.9.2**
 - `Expo` **39**

**Additional context**
none

**Comment by LonelyCpp** [comment]
this is default behaviour on ipad safari for some reason. Try changing the user agent string to emulate a desktop browser.

eg: 
```
webViewProps={
  {
    userAgent: isIpad ? `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36` : null
  }
}
```

(since this is working on all other devices, its better if you change userAgent only on ipad devices. You can use [device-info](https://github.com/react-native-device-info/react-native-device-info) for this)

**Comment by LonelyCpp** [comment]
you can try some more user agent string from this [gist](https://gist.github.com/svbutko/23f7dd3276d67567301a1026e09fe6df#file-useragenthelper-ts)

**Comment by matsu0228** [comment]
Thanks for the advice.

UA `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36`  didn't solve the problem, but `Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/ 604.1.21 (KHTML, like Gecko) Version/ 12.0 Mobile/17A6278a Safari/602.1.26` (your gist's value) did. 

I have no problem having this issue closed.

```
const isIos = Platform.OS === "ios";
const isIpad = isIos && (Platform as PlatformIOSStatic).isPad;


  <YoutubePlayer
          webViewProps={
            !isIpad
              ? null
              : {
                  userAgent:
                    "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/ 604.1.21 (KHTML, like Gecko) Version/ 12.0 Mobile/17A6278a Safari/602.1.26"
                }
          }
          ...
/>
```
